### ISSUE TITLE
mscorlib.dll run fail

### ISSUE THREAD

**Issue by waji3000** [mono/mono#12286]
1. system: win7 x64, vs 2017 15.9.2
2. Follow "Compiling Mono on Windows without Cygwin"(https://www.mono-project.com/docs/compiling-mono/windows/no-cygwin/), i get mono-sgen.exe and mscorlib.dll.
3. copy mono-sgen.exe and other files to folder mono
rename mono-sgen.exe to mono.exe 
copy mscorlib.dll and other files to folder mono\lib\mono\4.5
4.Then test, hello.cs
using System;
namespace TestMONO
{
    static class Program
    {
        static void Main()
        {
           Console.WriteLine("hello mono!");
           Console.ReadLine();
        }
    }
}
5. cmd to mono
lib\mono\4.5\mcs hello.cs
bin\mono.exe hello.exe

The error message is as follows：
Unhandled Exception:
Nested exception detected.
Original Exception: at TestMONO.Program.Main () [0x00000] in <887a017aab73435ea2a8d85ed2cb90e8>:0

Nested exception:at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider,string,System.ParamsArray) [0x003a6] in <7ef7898f75d54dc2a73fabebfda62a
89>:0 
at System.Text.StringBuilder.AppendFormat (string,object) [0x00009] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Diagnostics.StackTrace.AddFrames (System.Text.StringBuilder,bool,bool&) [0x0011f] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Diagnostics.StackTrace.ToString () [0x00083] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Diagnostics.StackTrace.ToString (System.Diagnostics.StackTrace/TraceFormat) [0x00001] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Environment.GetStackTrace (System.Exception,bool) [0x0001a] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Exception.GetStackTrace (bool) [0x00056] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Exception.ToString (bool,bool) [0x00099] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Exception.ToString (bool,bool) [0x00053] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Exception.ToString () [0x00001] in <7ef7898f75d54dc2a73fabebfda62a89>:0

[ERROR] FATAL UNHANDLED EXCEPTION: Nested exception detected.
Original Exception: at TestMONO.Program.Main () [0x00000] in <887a017aab73435ea2a8d85ed2cb90e8>:0

Nested exception:at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider,string,System.ParamsArray) [0x003a6] in <7ef7898f75d54dc2a73fabebfda62a
89>:0
at System.Text.StringBuilder.AppendFormat (string,object) [0x00009] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Diagnostics.StackTrace.AddFrames (System.Text.StringBuilder,bool,bool&) [0x0011f] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Diagnostics.StackTrace.ToString () [0x00083] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Diagnostics.StackTrace.ToString (System.Diagnostics.StackTrace/TraceFormat) [0x00001] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Environment.GetStackTrace (System.Exception,bool) [0x0001a] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Exception.GetStackTrace (bool) [0x00056] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Exception.ToString (bool,bool) [0x00099] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Exception.ToString (bool,bool) [0x00053] in <7ef7898f75d54dc2a73fabebfda62a89>:0
at System.Exception.ToString () [0x00001] in <7ef7898f75d54dc2a73fabebfda62a89>:0

5. Replace the mscorlib.dll compiled by myself with the file in the mono installation package(mono-5.18.0.225-gtksharp-2.12.45-win32-0.msi)
everything is OK, i get the right result.

What happened and how to solve it?
Thanks!

**Comment by marek-safar** [comment]
@lateralusX could you help?

**Comment by waji3000** [comment]
@lateralusX  could you help? thanks.

**Comment by lateralusX** [comment]
I have seen this as well (even though this is not my normal workflow). I talked with @kg yesterday, since there are build errors when building the BCL using bcl.sln (the use case you are running), looks like this broke during december and affects mscorlib.dll. Maybe @kg could take a look at the build issues in bcl.sln first to make sure it works as expected. I believe that the short term solution for you is to use the cygwin workflow until this gets fixed.

**Comment by lateralusX** [comment]
Do you get any errors when doing the bcl.sln build using net_4x release profile? Also make sure you make a clean BCL build if you done one in the past.

Do you get the same error if you try to run directly from your local build folders, not doing the copy steps as described above?

**Comment by lateralusX** [comment]
Just tried this on a clean mono master checkout, building the runtime using mono.sln (64-bit release) and then BCL using bcl.sln (net_4x release) and run a simple console app directly from local build BCL worked as expected (setting MONO_PATH to the BCL located in the build tree). There are still a number of build errors in bcl.sln (like mcs for example), but still looks like the BCL works as expected for the test application.

**Comment by lateralusX** [comment]
Yes, the errors in bcl.sln are still there and I see them on my machine as well when doing the build without cygwin. If you believe that you resolved the problem specific to this issue I believe it would be best to close this issue and I can open up a new issue around the specific build errors I have on bcl.sln and see if we could get that fixed. Sounds reasonable?

**Comment by lateralusX** [comment]
blc.sln build errors should be fixed by https://github.com/mono/mono/pull/12672 and I believe that should resolve this issue as well.

**Comment by waji3000** [comment]
Do follow:
[ <img alt="@lateralusX" width="20" height="20" src="https://avatars3.githubusercontent.com/u/11529140?s=60&amp;v=4"> ](/lateralusX)
` [Fix build errors for net_4_x bcl.sln build](/mono/mono/pull/12672/commits/6b749b647072a19e1715e458971789b09e2a3caa)`

I get new mcs.exe
use: 
set MONO_PATH=F:\mono\lib\mono\4.5
F:\mono\bin>mono f:\mono\lib\mono\4.5\mcs.exe
But the error is still exist.

Unhandled Exception:
Nested exception detected.
Original Exception: at Mono.CSharp.Driver.Main (string[]) [0x0001a] in <0c53d3c8bcab4164903cd2d9c8335fb5>:0

Double-click mcs.exe, the message is:
This application requires one of the following versions of the .net framework:Mono
So '--nostdlib' is work.
