### ISSUE TITLE
Xamarin.iOS Threadpool randomly halts when app is suspended and doesn't recover when resumed

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#12318]
_From @UmeshKanyal on June 4, 2018 19:35_

We are facing exactly the same issue as mentioned in [Bug58633](https://bugzilla.xamarin.com/show_bug.cgi?id=58633#c12)
Do we have any resolution to the above issue?

We also use Bluetooth, geofence, beacon, background location, background fetch. 
The ThreadPool randomly stops processing when the app is suspended and brought to the foreground. The main thread keeps on working but no background thread.
We have observed this issue on one specific iPhone 6s with 11.4 device, it works pretty well on rest of the other devices.

_Copied from original issue: xamarin/xamarin-macios#4178_

**Comment by rolfbjarne** [comment]
_From @dalexsoto on June 5, 2018 16:55_

Hello @UmeshKanyal any chance you have a reproducible test case for this scenario? if not could you provide some logs using this suggestion https://bugzilla.xamarin.com/show_bug.cgi?id=58633#c7?

**Comment by rolfbjarne** [comment]
_From @UmeshKanyal on June 5, 2018 20:36_

Hi @dalexsoto, I am using the Visual studio for mac, not sure how can I set 'MONO_LOG_LEVEL=debug' and 'MONO_LOG_MASK=threadpool'.

**Comment by rolfbjarne** [comment]
_From @jonathanantoine on December 28, 2018 8:59_

Hello. Any update on this ? This is quite frightening to have this bug in the wild :(


@dalexsoto I think I have a repro for this issue and I created a dedicated issue : https://github.com/xamarin/xamarin-macios/issues/5333 

Can you help me on this ?

**Comment by rolfbjarne** [comment]
_From @jgiacomini on December 28, 2018 11:20_

Same for me I had this bug on one my app :(
I don't know how to solve it :'(

**Comment by rolfbjarne** [comment]
The environment variables can be set by adding the following to the additional mtouch arguments in the project's iOS Build options:

    --setenv:MONO_LOG_LEVEL=debug --setenv:MONO_LOG_MASK=threadpool

Any output will be printed to the Application Output in the IDE.

**Comment by rolfbjarne** [comment]
I'm also moving this issue to the mono repo, since that's where the threadpool code is.

**Comment by rolfbjarne** [comment]
@luhenry does the threadpool use sockets? If so, this might be relevant: https://developer.apple.com/library/archive/technotes/tn2277/_index.html

**Comment by jahmai** [comment]
Glad to see this issue finally getting some attention. Subscribed.

**Comment by marek-safar** [comment]
@luhenry could you please assess the impact?

**Comment by luhenry** [comment]
@rolfbjarne the threadpool in itself doesn't uses sockets. The implementation of how the threadpool wakes up threads has changed as well, it went from a cond variable to a semaphore. So I am curious if it still reproduces with the latest version of Xamarin.iOS.

**Comment by jahmai** [comment]
@luhenry We accidentally reverted our workaround for this issue back around September ‘18 (using the latest Xam version at the time) and the issue reproduced. Did the latest build at that time include the semaphore change?

**Comment by luhenry** [comment]
@jahmai VS 15.8 was the first release with the switch from cond variable to semaphore. Is that the version you tried back in September 2018?

**Comment by jahmai** [comment]
@luhenry Going by appstore logs, our bug was released on August 15 (AEST). According to the VS release notes, 15.8 was first released on August 14 (EST?). It is highly unlikely we updated to 15.8 the day we released, but do you know of any way we can confirm if we have the IPA? (The assemblies in the IPA are all stripped of code - just method signatures, but there are AOT'd binaries of things like Xamarin.iOS).

**Comment by rolfbjarne** [comment]
> It is highly unlikely we updated to 15.8 the day we released, but do you know of any way we can confirm if we have the IPA?

The app's Info.plist contains the Xamarin.iOS version used to build it:

```xml
<key>com.xamarin.ios</key>
<dict>
	<key>Version</key>
	<string>12.2.1.9 (d15-9: 628409554)</string>
</dict>
```

**Comment by jahmai** [comment]
Seems not: 11.12.0.4 (d15-7: 64fece5f)
So I'll have to attempt a reproduction when I have some time.

**Comment by dkornev** [comment]
Confirm that it's still reproducible with Xamarin.iOS 12.2 and Mono 5.16

**Comment by jahmai** [comment]
@rolfbjarne Since @dkornev confirmed this was still an issue back in Feb, is there any energy to look further into this?

**Comment by rolfbjarne** [comment]
@marek-safar:

> Since @dkornev confirmed this was still an issue back in Feb, is there any energy to look further into this?

**Comment by steveisok** [comment]
@rolfbjarne Isn't this the same issue?  https://github.com/xamarin/xamarin-macios/issues/7080

**Comment by rolfbjarne** [comment]
@steveisok 

> @rolfbjarne Isn't this the same issue? [xamarin/xamarin-macios#7080](https://github.com/xamarin/xamarin-macios/issues/7080)

It's related, but not the same: that issue is about the workaround that was put in place because of this bug.

**Comment by jahmai** [comment]
The workaround in #5463 doesn't help *this* issue. This issue affects everything that sits on top of the mono threadpool, not just NSUrlSessionHandler.

**Comment by steveisok** [comment]
Can you post some sample code where I can test?  I've got a hacked up XI build and I can test it all out.  

As I said in the other issue, I'm on a d16-3 build and haven't been able to reproduce after removing that workaround.

**Comment by jahmai** [comment]
If you read https://bugzilla.xamarin.com/show_bug.cgi?id=58633 I had no luck creating a test case for this because it happens;

- Only on a real device
- Not when attached to a debugger (the app needs to be suspended which kills the debugging session)
- You need real OS events to trigger it like bluetooth, crossing a geofence, a silent push notification.

I have my own testbed using our actual app running in the background with a few geofences set, combined with a special native XCode application that runs a location simulation (gpx file) which causes the physical device to report locations that move in and out of geofences over a long period of time. With this setup that causes a geofence crossing every 30 seconds or so, it takes anywhere between 12 and 50 hours to reproduce.

**Comment by lambdageek** [comment]
This may be addressed by https://github.com/mono/mono/pull/17927 (master) https://github.com/mono/mono/pull/17944 (2019-10, mono 6.8).  Difficult to say for sure without a reproduction that demonstrates the issue.

**Comment by jahmai** [comment]
@lambdageek Any ideas when this will hit Stable? I may have time to test this thoroughly in a few weeks.

**Comment by akoeplinger** [comment]
@jahmai you can try a build from xamarin-macios master which should contain that change to verify: https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/master/b3bc04c919a00b82c67fc7157a03b353f8b75f38/1019/package/notarized/xamarin.ios-13.15.0.111.pkg

**Comment by chamons** [comment]
@jahmai - Please see https://github.com/xamarin/xamarin-macios/issues/7080#issuecomment-609945804 for details on how to test.

**Comment by jahmai** [comment]
@chamons You guys keep missing the mark on this. This issue has absolutely nothing to do with NSUrlSessionHandler or HttpClient, we don't even use those. This issue is in the native mono thread-pool. Please read https://xamarin.github.io/bugzilla-archives/58/58633/bug.html another 5 times.

**Comment by mandel-macaque** [comment]
@jahmai what @chamons wanted to express, and might have been lost, is that we have released a version of Xamarin.iOS that contains a mono version with the fix for the Threadpool issue, which is the root of several issues, one of them, and most common one, is the HttpClient one.

We have tried to reproduce the issue, but we are not able (maybe hardware dependent). So we would appreciate that any users that have such hardware to test with the httpclient, which is the simplest way, since we only need to perform a request that takes a long time and put the application in the background.

Nevertheless, if you have an application that can easily reproduce the issue, it would be great if you can test it with the latests Xamarin.iOS pkg, which contains mono 2020-02 and that in theory has resolved the problem.

**Comment by jahmai** [comment]
@mandel-macaque Ok, I'll setup my reproduction testbed again today and let it run. But note that IO wasn't necessary to cause this issue on my tesbed, the app just had to be suspended repeatedly until eventually the threadpool became unresponsive.

**Comment by mandel-macaque** [comment]
@jahmai oh, yes, fully agree with you. The problem is that the Threadpool gets in an unknown state. IO is just the simples way to test it. It is easier that having a user sending the app to the background in the right moment. If you can confirm that the issue does not longer happen would be greatly appreciated, we have not been able to find a device to reproduce it so far.

Thanks in advance.

**Comment by jahmai** [comment]
@mandel-macaque Test bed is running. Latest MacOS, Xamarin.iOS, XCode and running on an iPhone SE with iOS 13.4. It used to take up to 4 days to reproduce, but usually within 2. If it runs for 7 days I'll call it solved, else I'll post the logs here with if it fails. I have 'MONO_LOG_LEVEL=debug' and 'MONO_LOG_MASK=threadpool' set as well.

**Comment by pilcherd** [comment]
@jahmai Hi, did it lock up?  [watching thread due some issues that might be related to this thread].

**Comment by jahmai** [comment]
@pilcherd

The test is still running (not locked up). _However_, the testbed doesn't quite run as it used to - it seems XCode's GPS location simulation doesn't work properly at the moment, so I am getting much less movement and therefore much fewer events that cause the app to be suspended.

I was intending to place our app on my phone and do some real-life testing (usually it would break within 1-2 weeks of normal background tracking with geofences between work and home), but Australia is currently on lockdown due to COVID-19 so I pretty much don't leave the house at the moment, and it is expected to be this way for many weeks yet.

**Comment by pilcherd** [comment]
So we have an app that does Bluetooth and GPS etc.  We had it have issues running background threads on last year and found an SDK version that we pinned it at that worked reliably.  Recently the Azure Pipelines retired the MacOS image that supported the SDK and we had to build with a more recent SDK.  Within 2 days the issue was back on two test phones.

I checked out the latest SDK/VS/XCode etc. that reportedly includes this fix and did a local build outside of the pipeline (latest is not there yet).  No code changes except SDK build version and so far no 'lock ups'. My test has been running 6 days now on those phones so looking 'hopeful'.  For us, the symptom was the BLE advertisement would resume the app in in background but no tasks would then run.

The nature of this issue appeared to be quite random in terms of time before occurring, and in the past we even had it take a couple of weeks before it occurred. I thought I'd post this as positive feedback so far given the apparent contrast between SDK builds.

**Comment by jahmai** [comment]
Thanks, @pilcherd. FWIW, our testbed is still running without issues. I'm still too nervous to just turn off our workarounds, however, I also see no reason to hold up this ticket any longer (as you said, it's so random that sometimes it actually takes a couple of weeks to reproduce). Once I am able I will do some real-life testing scenarios and if the problems come back then I'll make a new ticket.

**Comment by pilcherd** [comment]
@jahmai I'm leaving our test running here and will update in 8 days if still no issues.

**Comment by jahmai** [comment]
Hi all, just dropping back to say we've done some fairly significant testing of this and the issue appears to be resolved. We will be releasing a production version including the fix next week. Well done!

**Comment by akoeplinger** [comment]
Thanks for the follow-up and good news @jahmai !

I'm closing this issue then :)
