### ISSUE TITLE
Regression: LLVM/SSSE4.1 issue reopen in 5.18.0.268-0xamarin1 .debs

### ISSUE THREAD

**Issue by squirrelboot** [mono/mono#13361]
## Steps to Reproduce

1. sudo apt-get update && apt-get dist-upgrade
2. sudo dpkg --configure -a

### Current Behavior

Mono has worked without issues for months and months. After doing a standard 'sudo apt-get update && apt-get dist-upgrade' many errors and failures occurred. 

Now I am unable to use apt-get, nor fix it with dpkg, etc. 

I do not know what to do. Help!

### Expected Behavior

That the software would update, and things would move along normally. 

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.18.0.268 (tarball Thu Feb 28 15:25:36 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

## Stacktrace

Original/First time it occurred:
http://pasted.co/9ef63fd0

Current, when I try to run 'sudo dpkg --configure -a':
http://pasted.co/eb666246

I cannot proceed past this point. 

## Further Information
I am constantly just thrown back to this

**Comment by directhex** [comment]
What processor do you have? I've heard a few reports like this but have been unable to reproduce locally

**Comment by squirrelboot** [comment]
I have an Intel Atom on this board:

https://www.asus.com/Motherboards/AT3IONTI_DELUXE/

**Comment by kevinpawsey** [comment]
If it helps, I have a core2duo, an HP Microserver, and seeing a similar issue when doing an apt upgrade of mono.

Is there anything that I can run that will help point you in the right direction?

**Comment by directhex** [comment]
Which model of Core 2 Duo, exactly?

**Comment by kevinpawsey** [comment]
our posts crossed... I just updated with some info about my system in my post above

Let me know if you need anything else at all

**Comment by directhex** [comment]
can you run `dpkg-reconfigure -plow libmono-corlib4.5-cil` and paste the full output?

**Comment by kevinpawsey** [comment]
here it is:

`sudo dpkg-reconfigure -plow libmono-corlib4.5-cil

Mono precompiling /usr/lib/mono/4.5/mscorlib.dll for amd64 (LLVM disabled due to missing SSE4.1)...`

**Comment by kevinpawsey** [comment]
at the moment I have not got a 'broken' update... this is before the update... when my upgrade broke I rolled back (thanks to BTRFS snapshotting!!)... so my system is working at the moment

**Comment by directhex** [comment]
I think it's telling that both your CPU and @squirrelboot's lack SSE4 support, but literally nothing relevant to that has changed between 5.18.0.240 and 5.18.0.268.

Can you erase /usr/lib/mono/aot-cache and try running the upgrade again?

**Comment by kevinpawsey** [comment]
this is the contents of that folder at the moment...

ls /usr/lib/mono/aot-cache
amd64
ls /usr/lib/mono/aot-cache/amd64/
csc.exe.so  Microsoft.CodeAnalysis.CSharp.dll.so  Microsoft.CodeAnalysis.VisualBasic.dll.so  System.Collections.Immutable.dll.so  vbc.exe.so
mcs.exe.so  Microsoft.CodeAnalysis.dll.so         mscorlib.dll.so                            System.Reflection.Metadata.dll.so    VBCSCompiler.exe.so

I will erase and retry the upgrade...

**Comment by kevinpawsey** [comment]
no, it crashed again during the upgrade... I have a broken install now... is there anything that I can get you now that will point to the issue?

**Comment by kevinpawsey** [comment]
This is the last lines of the upgrade ... this debug info then repeats several times

Setting up mono-gac (5.18.0.268-0xamarin7+ubuntu1804b1) ...
* Installing 1 assembly from libnunit-console-runner2.6.3-cil into Mono
/proc/self/maps:
4125e000-4126e000 rwxp 00000000 00:00 0 
41e09000-41e29000 rwxp 00000000 00:00 0 
558264cef000-55826513b000 r-xp 00000000 00:18 13477                      /usr/bin/mono-sgen
55826533a000-558265341000 r--p 0044b000 00:18 13477                      /usr/bin/mono-sgen
558265341000-558265346000 rw-p 00452000 00:18 13477                      /usr/bin/mono-sgen
558265346000-55826535d000 rw-p 00000000 00:00 0 
558266081000-5582662d9000 rw-p 00000000 00:00 0                          [heap]
7fc830000000-7fc830021000 rw-p 00000000 00:00 0 
7fc830021000-7fc834000000 ---p 00000000 00:00 0 
7fc836400000-7fc836500000 rw-p 00000000 00:00 0 
7fc8365c0000-7fc8365c1000 ---p 00000000 00:00 0 
7fc8365c1000-7fc8365c2000 rw-p 00000000 00:00 0 
7fc8365c2000-7fc8365ca000 ---p 00000000 00:00 0 
7fc8365ca000-7fc8367c1000 rw-p 00000000 00:00 0 
7fc8367c1000-7fc836d7d000 r-xp 00000000 00:18 365                        /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7fc836d7d000-7fc836f7c000 ---p 005bc000 00:18 365                        /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7fc836f7c000-7fc836f7d000 r--p 005bb000 00:18 365                        /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7fc836f7d000-7fc836f7e000 rw-p 005bc000 00:18 365                        /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7fc836f7e000-7fc836fa8000 rw-p 00000000 00:00 0 
7fc836fa8000-7fc8373ff000 r--p 00000000 00:18 13352                      /usr/lib/mono/4.5/mscorlib.dll
7fc8373ff000-7fc8383ff000 rw-p 00000000 00:00 0 
7fc8383ff000-7fc838400000 ---p 00000000 00:00 0 
7fc838400000-7fc839000000 rw-p 00000000 00:00 0 
7fc839043000-7fc839090000 r--p 00000000 00:18 63034                      /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll
7fc839090000-7fc839144000 rw-p 00000000 00:00 0 

Debug info from gdb:


=================================================================
	External Debugger Dump:
=================================================================
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
Aborted (core dumped)
E: installing Assembly /usr/lib/cli/nunit-console-runner-2.6.3/nunit-console-runner.dll failed
E: Installation of libnunit-console-runner2.6.3-cil with /usr/share/cli-common/runtimes.d/mono failed
* Installing 1 assembly from libnunit-core2.6.3-cil into Mono
/proc/self/maps:
40355000-40365000 rwxp 00000000 00:00 0 
4170f000-4172f000 rwxp 00000000 00:00 0 
556857763000-556857baf000 r-xp 00000000 00:18 13477                      /usr/bin/mono-sgen
556857dae000-556857db5000 r--p 0044b000 00:18 13477                      /usr/bin/mono-sgen
556857db5000-556857dba000 rw-p 00452000 00:18 13477                      /usr/bin/mono-sgen
556857dba000-556857dd1000 rw-p 00000000 00:00 0 
556858990000-556858be8000 rw-p 00000000 00:00 0                          [heap]
7f7714000000-7f7714021000 rw-p 00000000 00:00 0 
7f7714021000-7f7718000000 ---p 00000000 00:00 0 
7f7719600000-7f7719700000 rw-p 00000000 00:00 0 
7f77197c1000-7f7719d7d000 r-xp 00000000 00:18 365                        /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7f7719d7d000-7f7719f7c000 ---p 005bc000 00:18 365                        /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7f7719f7c000-7f7719f7d000 r--p 005bb000 00:18 365                        /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7f7719f7d000-7f7719f7e000 rw-p 005bc000 00:18 365                        /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7f7719f7e000-7f7719fa8000 rw-p 00000000 00:00 0 
7f7719fa8000-7f771a3ff000 r--p 00000000 00:18 13352                      /usr/lib/mono/4.5/mscorlib.dll
7f771a3ff000-7f771b3ff000 rw-p 00000000 00:00 0 
7f771b3ff000-7f771b400000 ---p 00000000 00:00 0 
7f771b400000-7f771c000000 rw-p 00000000 00:00 0 
7f771c056000-7f771c0a3000 r--p 00000000 00:18 63034                      /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll
7f771c0a3000-7f771c0a4000 ---p 00000000 00:00 0 
7f771c0a4000-7f771c0a5000 rw-p 00000000 00:00 0 
7f771c0a5000-7f771c0ad000 ---p 00000000 00:00 0 
7f771c0ad000-7f771c358000 rw-p 00000000 00:00 0 
7f771c35c000-7f771c3c6000 r--p 00000000 00:18 13531                      /usr/lib/mono/4.5/gacutil.exe

[repeated... until] ...

Debug info from gdb:


=================================================================
	External Debugger Dump:
=================================================================
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
Aborted (core dumped)
E: installing Assembly /usr/share/cli-common/policies.d/libnunit-util2.6.3-cil/policy.2.6.nunit.util.dll failed
E: Installation of policy.2.6.nunit.util with /usr/share/cli-common/runtimes.d/mono failed
dpkg: error processing package mono-gac (--configure):
 installed mono-gac package post-installation script subprocess returned error exit status 29
dpkg: dependency problems prevent configuration of mono-runtime-common:
 mono-runtime-common depends on mono-gac (= 5.18.0.268-0xamarin7+ubuntu1804b1); however:
  Package mono-gac is not configured yet.

dpkg: error processing package mono-runtime-common (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libmono-system-core4.0-cil:
 libmono-system-core4.0-cil depends on mono-runtime-common (>= 5.18.0.268); however:
  Package mono-runtime-common is not configured yet.

dpkg: error processing package libmono-system-core4.0-cil (--configure):
 dependency No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                                      No apport report written because the error message indicates its a followup error from a previous failure.
                                           No apport report written because MaxReports is reached already
                                                                                                         No apport report written because MaxReports is reached already
                                                                                                                                                                       No apport report written because MaxReports is reached already
                                                No apport report written because MaxReports is reached already
                                                                                                              problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libmono-system4.0-cil:
 libmono-system4.0-cil depends on mono-runtime-common (>= 5.18.0.268); however:
  Package mono-runtime-common is not configured yet.

dpkg: error processing package libmono-system4.0-cil (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libmono-system-xml4.0-cil:
 libmono-system-xml4.0-cil depends on libmono-system4.0-cil (>= 4.0.0~alpha1); however:
  Package libmono-system4.0-cil is not configured yet.

dpkg: error processing package libmono-system-xml4.0-cil (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libmono-system-security4.0-cil:
 libmono-system-security4.0-cil depends on libmono-system-xml4.0-cil (>= 3.12.0); however:
  Package libmono-system-xml4.0-cil is not configured yet.
 libmono-system-security4.0-cil depends on libmono-system4.0-cil (>= 4.0.0~alpha1); however:
  Package libmono-system4.0-cil is not configured yet.

dpkg: error processing package libmono-system-security4.0-cil (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libmono-system-configuration4.0-cil:
 libmono-system-configuration4.0-cil depends on libmono-system4.0-cil (>= 4.0.0~alpha1); however:
  Package libmono-system4.0-cil is not configured yet.

dpkg: error processing package libmono-system-configuration4.0-cil (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mono-gac
 mono-runtime-common
 libmono-system-core4.0-cil
 libmono-system4.0-cil
 libmono-system-xml4.0-cil
 libmono-system-security4.0-cil
 libmono-system-configuration4.0-cil
E: Sub-process /usr/bin/dpkg returned an error code (1)

Let me know if you need any other information... I will hold off rolling back the snapshot until I hear back from you

**Comment by directhex** [comment]
Roll it back. I'll think about how I can plausibly reproduce locally.

**Comment by kevinpawsey** [comment]
ok, cool... thank you for that... let me know if you need me to try anything else

**Comment by directhex** [comment]
OK, I think this is just https://github.com/mono/mono/issues/12182 - looks like the change to avoid LLVM AOT on non-SSE4 hardware was somehow reverted?

**Comment by directhex** [comment]
Shit, I see what happened.

The LLVM/SSSE4.1 fix went in with 5.18.0.225-0xamarin13

But the packaging branch used by 5.18.0.268 came right after 5.18.0.225-0xamarin11 (!) for some reason. Probably something I messed up. Point is, it's missing the key commit.

I've pushed, and scheduled a build.

**Comment by directhex** [comment]
Keep an eye on https://jenkins.mono-project.com/view/Releases/job/ng-release-generate-debian-packages/1544/

**Comment by squirrelboot** [comment]
Thank you guys for looking at this. I only request that you somehow help me fix it when that build is done.  I cannot get it to do anything other than spit out those errors like in my OP. So even if this build fixes it, I don't know how to make the system continue. I'm kind of new to this stuff. Just ok at bug reporting. 🙈

**Comment by directhex** [comment]
`sudo dpkg --purge mono-llvm-support` then deleting the contents of /usr/lib/mono/aot-cache should fix you up.

**Comment by kevinpawsey** [comment]
is this safe to try to update again?  I have seen that it has compiled successfully now, I have done an "apt update" but the components are still showing as 5.18.0.268, is this the right version?

**Comment by kevinpawsey** [comment]
You're a star @directhex ... I have just successfully completed the upgrade of mono completely

@squirrelboot hopefully if you follow the above command you should be good to get a working system again

**Comment by directhex** [comment]
Yeah, this was my screwup, not sure how I branched from a point without the LLVM/SSSE4.1 fix.

**Comment by kevinpawsey** [comment]
these things happen... it is fixed now... just a case of hoping that @squirrelboot manages to correct his too... the moral of this story is... BTRFS does have it's uses! lol

**Comment by directhex** [comment]
I'm marking the issue closed, for bookkeeping (since it is), but any user support on the problem, please feel free to poke here, or on gitter, or check the historical references in the comments of https://github.com/mono/mono/issues/12182

**Comment by squirrelboot** [comment]
> `sudo dpkg --purge mono-llvm-support` then deleting the contents of /usr/lib/mono/aot-cache should fix you up.

This seems to have correctly fixed the issue of the errors. I then performed apt update/upgrade. 

I also saw this in there ^_^ 
[https://i.imgur.com/UM9ECfG.png](https://i.imgur.com/UM9ECfG.png)
