### ISSUE TITLE
System.Runtime.CompilerServices.UnsafeTests attempting to JIT compile on iOS devices

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#13479]
## Steps to Reproduce

1. Build xamarin-macios master
2. Run `[xUnit] Mono SystemRuntimeCompilerServicesUnsafeXunit - iOS Unified 64-bits - device - Debug`
3. A few tests fail

Looks like this was missed in the 2018-10 integration, but it happens on 2019-02 as well.

### Current Behavior

```
   Test name: System.Runtime.CompilerServices.UnsafeTests.SizeOf<SByte>(expected: 1, valueUnused: 0)
   Test case: System.Runtime.CompilerServices.UnsafeTests.SizeOf
   Exception messages: System.ExecutionEngineException : Attempting to JIT compile method 'int System.Runtime.CompilerServices.Unsafe:SizeOf<sbyte> ()' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

   Exception stack traces:   at System.Runtime.CompilerServices.UnsafeTests.SizeOf[T] (System.Int32 expected, T valueUnused) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-02/ios/release/external/corefx/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs:137 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Users/alexander/dev/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:391 
   Execution time: 0,0064214
```

### Expected Behavior

No failures.

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**: 2018-10

**Comment by marek-safar** [comment]
@vargaz could you please investigate

**Comment by vargaz** [comment]
Where is this test suite ?

**Comment by akoeplinger** [comment]
@vargaz it's essentially https://github.com/mono/mono/blob/master/mcs/class/System.Runtime.CompilerServices.Unsafe/System.Runtime.CompilerServices.Unsafe_xtest.dll.sources

**Comment by vargaz** [comment]
This was already fixed in master by b8b24693809bc676a524f68a894d677781850d0a.

**Comment by akoeplinger** [comment]
@vargaz I opened a backport PR for 2019-02 but 2018-10 has conflicts, could you please manually backport?

**Comment by vargaz** [comment]
Not sure we should backport this, its somewhat of a risky change.

**Comment by akoeplinger** [comment]
As discussed on Slack it's not fixed by the commit.

**Comment by marek-safar** [comment]
@vargaz as reported by Alexander, the issue is still unresolved
