### ISSUE TITLE
Pango modules.cache contains jenkins builder path

### ISSUE THREAD

**Issue by Therzok** [mono/mono#14181]
## Steps to Reproduce

1. It seems to happen during update of VSMac
2. Observe sometimes font print out squares
3. Is it possible that the post-install script is not being run or has errors?

### Current Behavior

1. Cause: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596552
2. Symptoms: https://developercommunity.visualstudio.com/content/problem/228583/vs2017-for-mac-setup-%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81.html

### Expected Behavior

Fonts should work.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:

I think it's been going on for a while

**Comment by Therzok** [comment]
cc @alexischr

**Comment by alexischr** [comment]
I installed `Mono JIT compiler version 6.0.0.6 (2019-02/12cadb2b21d Wed Feb  6 03:24:22 PST 2019)`

and looked at the installed `pango.modules` - I see 
```
# Pango Modules file
# Automatically generated file, do not edit
#
# ModulesPath = /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/pango/1.8.0/modules
#
/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/pango/1.8.0/modules/pango-arabic-lang.so ArabicScriptEngineLang PangoEngineLang PangoRenderNone arabic:*
/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/pango/1.8.0/modules/pango-basic-coretext.so BasicScriptEngineCoreText PangoEngineShape PangoRenderCoreText common:
/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/pango/1.8.0/modules/pango-indic-lang.so devaIndicScriptEngineLang PangoEngineLang PangoRenderNone devanagari:*
...
```

so no builder paths. So yeah the postinstall must be failing under some conditions only. Do you have a reproduction @Therzok ?

**Comment by Therzok** [comment]
Should this be closed?

**Comment by Therzok** [comment]
vsts ticked has been closed, I'll close this too and reopen if we see it again.

**Comment by kdubau** [comment]
You can repro the font rendering issue by installing a different Mono while VS4M is running (perhaps not the smartest idea but might offer some insight).

![image](https://user-images.githubusercontent.com/2809202/66408886-c1248e80-e9bd-11e9-904d-fc0f99314a3d.png)

**Comment by kdubau** [comment]
@Therzok I don't have permission to re-open, could you?

**Comment by Therzok** [comment]
Done!

**Comment by lambdageek** [comment]
If this happens to anyone, could you please collect:

1. The contents of ever `.log` file in `/Library/Frameworks/Mono.framework/Versions/Current`
2. the output of:
 ```
      cd /Library/Frameworks/Mono.framework/Versions/Current
      file bin/fc-cache bin/pango-querymodules bin/gdk-pixbuf-query-loaders 
  ```

**Comment by marek-safar** [comment]
I can reproduce it on my machine when Mono installer failed to finish. I don't have any .log file under `/Library/Frameworks/Mono.framework/Versions/Current`

The output of file gdk-pixbuf-query-loaders 

```
in/fc-cache:                 Mach-O universal binary with 2 architectures: [i386:Mach-O executable i386] [x86_64:Mach-O 64-bit executable x86_64]
bin/fc-cache (for architecture i386):	Mach-O executable i386
bin/fc-cache (for architecture x86_64):	Mach-O 64-bit executable x86_64
bin/pango-querymodules:       Mach-O universal binary with 2 architectures: [i386:Mach-O executable i386] [x86_64:Mach-O 64-bit executable x86_64]
bin/pango-querymodules (for architecture i386):	Mach-O executable i386
bin/pango-querymodules (for architecture x86_64):	Mach-O 64-bit executable x86_64
bin/gdk-pixbuf-query-loaders: Mach-O universal binary with 2 architectures: [i386:Mach-O executable i386] [x86_64:Mach-O 64-bit executable x86_64]
bin/gdk-pixbuf-query-loaders (for architecture i386):	Mach-O executable i386
bin/gdk-pixbuf-query-loaders (for architecture x86_64):	Mach-O 64-bit executable x86_64
```

That's with Mono JIT compiler version 6.6.0.140 (2019-08/1b2e536b223 Wed Oct 23 17:31:53 EDT 2019)

@lambdageek what else to try?

**Comment by alexischr** [comment]
@marek-safar if you can reproduce the Mono installer failing, could you open the installer, go to Window->Installer Log and collect all output at the "Show all logs" detail level? We hope to see where the postinstall script failed.

**Comment by alexischr** [comment]
@marek-safar Also, does the problem persist when you restart VS4Mac? I was finally able to reproduce with @kdubau 's help, but that problem goes away with a restart, so it is not the persistent problem that some users seem to face.

**Comment by marek-safar** [comment]
@alexischr yes, the issue persists after VS4M restart (even machine restart).

**Comment by Therzok** [comment]
I think I've found the root cause of this problem:

Comparing an initial set of logs from @BretJohnson with some I had from mono, I found a few things that seemed to pop out:

I have pkg-config installed from brew, Bret does not, which runs this bit of code:

```
package_script_service: ./postinstall: ++ readlink /usr/local/bin/pkg-config
package_script_service: ./postinstall: + location=../Cellar/pkg-config/0.29.2_3/bin/pkg-config
package_script_service: ./postinstall: + case "$location" in
```

And bret's installer has this error:
```
package_script_service: ./postinstall: + for j in '$(ls man*/${i}.*)'
package_script_service: ./postinstall: + test '!' -e /usr/local/share/man/man5/mdoc.5
package_script_service: ./postinstall: + ln -sf /Library/Frameworks/Mono.framework/Versions/Current/share/man/man5/mdoc.5 /usr/local/share/man/man5/mdoc.5
package_script_service: ./postinstall: ln: /usr/local/share/man/man5/mdoc.5: No such file or directory
```

So looking over what the installer is running:

```
package_script_service: ./postinstall: + export 'PATH=/Library/Frameworks/Mono.framework/Versions/Current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/libexec'
package_script_service: ./postinstall: + PATH='/Library/Frameworks/Mono.framework/Versions/Current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/libexec'
package_script_service: ./postinstall: + gdk-pixbuf-query-loaders --update-cache
package_script_service: ./postinstall: + mkdir -p pango
package_script_service: ./postinstall: + pango-querymodules
package_script_service: ./postinstall: + pango-querymodules --update-cache
package_script_service: ./postinstall: + fc-cache
package_script_service: ./postinstall: + cd /Library/Frameworks/Mono.framework/Versions/Current/lib/gtk-2.0/2.10.0
package_script_service: ./postinstall: + gtk-query-immodules-2.0
package_script_service: ./postinstall: + echo Current: 6.12.0
package_script_service: ./postinstall: + pushd /Library/Frameworks/Mono.framework/Versions
package_script_service: ./postinstall: /Library/Frameworks/Mono.framework/Versions /Library/Frameworks/Mono.framework/Versions/Current/lib/gtk-2.0/2.10.0
```

And it seems that both commands successfully ran. The problem is that it doesn't look like the mono installer broke, but there are a few things I can see breaking in here.

pkg-config, instead of being resolved from the newly installed Mono, could be resolved from the system, in /usr/local/bin/pkg-config, or from the old mono installation, which would then setup the environment.

```
➜  ~ /Library/Frameworks/Mono.framework/Versions/Current/bin/pkg-config gdk-pixbuf-2.0 --print-variables
gdk_pixbuf_binary_version
exec_prefix
gdk_pixbuf_binarydir
prefix
libdir
includedir
gdk_pixbuf_cache_file
gdk_pixbuf_moduledir

➜  ~ /usr/local/bin/pkg-config gdk-pixbuf-2.0 --print-variables
bindir
gdk_pixbuf_binary_version
gdk_pixbuf_binarydir
gdk_pixbuf_cache_file
gdk_pixbuf_csource
gdk_pixbuf_moduledir
gdk_pixbuf_pixdata
gdk_pixbuf_query_loaders
includedir
libdir
pcfiledir
prefix
```

There are quite a few scenarios where I can see this breaking because the wrong pkg-config is being used at some point (i.e. old mono's pkg-config, system one). If any of the paths is absolute, it can run the package script on the _old_ installation instead of the new one.
