### ISSUE TITLE
Unable to get ANY proper ssl certificate validation (TLS 1.2) in mono.

### ISSUE THREAD

**Issue by Ub1Catcrush** [mono/mono#14311]
**The core issue is we cannot get a proper ssl certificate validation (TLS 1.2) running.
The attached program is to show current issues with SSL certificate validation in Mono.**
============================
[MonoSSLTest.zip](https://github.com/mono/mono/files/3137792/MonoSSLTest.zip)

Everything was tried on windows 10 with VS 2017 15.9.7.
used mono was is at state ofl 21.4.2019 with BTLS enabled.
The tryout is on console but our target platform is an embedded AOT mono on W64/XB1/PS4/Switch.

**1. Micosoft SDK**
---------------------
On microsofts windows sdk validating a certificate works flawlessly

A log for system validation can be found in _examplelogs\ssl_test_windows_system.log_
[ssl_test_windows_system.log](https://github.com/mono/mono/files/3137802/ssl_test_windows_system.log)

**2. Micosoft SDK with OpenSSL net (github openssl-net with 32bit 1.0.2r windows libs"):**
---------------------
On microsofts windows sdk also this way to validate a certificate works flawlessly

A log for openssl validation can be found in _examplelogs\ssl_test_windows_openssl.log_
[ssl_test_windows_openssl.log](https://github.com/mono/mono/files/3137801/ssl_test_windows_openssl.log)

**3. MONO legacy:**
---------------------

It simply quits with and exception during AuthenticateAsClient:

```
IOException The authentication or decryption has failed.
INNER IOException The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x0004b] in <2ba552739e354a84bf029a3cd0dcbc6d>:0 
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x0000e] in <5c715dc7cd084e1b9a6e9162f2fcbdc0>:0 
  at Mono.Net.Security.Private.LegacySslStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x0000e] in <5c715dc7cd084e1b9a6e9162f2fcbdc0>:0 
  at System.Net.Security.SslStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x00006] in <5c715dc7cd084e1b9a6e9162f2fcbdc0>:0 
  at Crossplatform.SSL.SystemCertificateVerificationUtil.VerifySSLCertificate (System.String host, System.Int32 port) [0x00050] in <2f4407c429034727b9796ee49fbaed84>:0 
```

A log can be found in _examplelogs\ssl_test_mono_legacy.log_
[ssl_test_mono_legacy.log](https://github.com/mono/mono/files/3137799/ssl_test_mono_legacy.log)

**4. MONO BTLS:**
---------------------

A list of 135 root certificates was imported to legacy and btls cert stores using cert-sync, certmgr was used to download all chain certs. 
Still the validation fails.
It seems simply not to be using the store certificates (though they are definitely available in .mono/certs/Trust and .mono/new-certs/Trust) and thus the certificate cannot be validated.
Addditionally there is no alternate way available, as I am not able to validate a chain separtely (then it always throws an empty certificate error during build).

```
Chain Status: PartialChain
AuthenticationException Authentication failed, see inner exception.
INNER MonoBtlsException Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at T:\mono-winaot\external\boringssl\ssl\handshake_client.c:1132
at Crossplatform.SSL.SystemCertificateVerificationUtil.VerifySSLCertificate (System.String host, System.Int32 port) [0x0007f] in <2f4407c429034727b9796ee49fbaed84>:0 
```

Already tried an update to the most current boringssl source, which did not change anything.

A log can be found in _examplelogs\ssl_test_mono_btls.log_
[ssl_test_mono_btls.log](https://github.com/mono/mono/files/3137798/ssl_test_mono_btls.log)

**5. MONO OpenSSL net (github openssl-net with 64bit 1.0.2r windows libs"):**
---------------------

The list of 135 root certificates is added to the validation request and the certificate can be validated on commandline (though on mono that crashes when the garbage collector is cleaning up afterwards).
So the issues here are:

1. The openssl code on mono (windows is just fine) is not exiting properly but crashes w/o any stacktrace when the garbage collector is cleaning up afterwards (on console). 
2. It is at least verifying on console (apart of the crash) but as soon as I tried it in "--debug" embedded environment it is simply exiting,
   before doing anything in the relevant code. W/O "--debug" I get at least an error "Failed to load AOT module 'mscorlib' while running in aot-only mode: doesn't match assembly."

A log can be found in _examplelogs\ssl_test_mono_openssl.log_
[ssl_test_mono_openssl.log](https://github.com/mono/mono/files/3137800/ssl_test_mono_openssl.log)

**Request**
============================
It would be awesome to get at least one way to AuthenticateAsClient (legacy, btls or openssl) working without any issues on windows and also later on XBoxOne/PS4/Switch!

**How to use the test**
============================

**Microsoft SDK**
---------------------
Compile the Debug version of the solution
Manually copy the libs/openssl_32 to the bin/Debug folder as windows requires the 32 bit libs.
Run MonoSSLTest\run_ssl_test.bat to execute the direkt windows sdk tests

which are

```
.\bin\Debug\MonoSSLTest.exe www.ubisoft.com 443 SYSTEM
.\bin\Debug\MonoSSLTest.exe www.ubisoft.com 443 OPENSSL
```
**MONO**
---------------------
Compile the Debug version of the solution
Manually copy the libs/openssl_64 to the bin/Debug folder as mono requires the 64 bit libs.

Run MonoSSLTest\import_certificates_to_mono.bat (be aware that you need to correct the path to your location of the cert-sync tool).
Run MonoSSLTest\run_mono_ssl_test.bat to execute the mono tests (be aware that you need to correct the MONO_PATH and of mono-sgen path to your locations).

which are

```
SET MONO_TLS_PROVIDER=legacy
mono-sgen.exe --debug .\bin\Debug\MonoSSLTest.exe www.ubisoft.com 443 SYSTEM

SET MONO_TLS_PROVIDER=btls
mono-sgen.exe --debug .\bin\Debug\MonoSSLTest.exe www.ubisoft.com 443 SYSTEM

mono-sgen.exe --debug .\bin\Debug\MonoSSLTest.exe www.ubisoft.com 443 OPENSSL
```

**Comment by Ub1Catcrush** [comment]
Adding log files yo you can view them without opening the zip file.
[ssl_test_mono_btls.log](https://github.com/mono/mono/files/3137798/ssl_test_mono_btls.log)
[ssl_test_mono_legacy.log](https://github.com/mono/mono/files/3137799/ssl_test_mono_legacy.log)
[ssl_test_mono_openssl.log](https://github.com/mono/mono/files/3137800/ssl_test_mono_openssl.log)
[ssl_test_windows_openssl.log](https://github.com/mono/mono/files/3137801/ssl_test_windows_openssl.log)
[ssl_test_windows_system.log](https://github.com/mono/mono/files/3137802/ssl_test_windows_system.log)

**Comment by lateralusX** [comment]
Short update, after investigation I have pinpointed the problem for trusted certificate validation problem when using Mono and boringssl/openss). First there are a couple of things to be aware of when setting things up in order for it to work under boringssl using the default certificate store locations.

* Certificates must be imported into default machine and/or user store using cert-sync.exe tools since that is the only version that support the new stores used by boringssl as well as supporting older legacy SSL/TLS providers.

* There is currently a bug in boringssl handling of X509_LOOKUP_add_dir. In openssl repro there are a couple of defines for path separator, but looks like boringssl made this part Unix specific, meaning that Windows paths won't work as expected. This needs to be patched in the boringssl version used by Mono in order to work (potentially in other places as well).

So in order for the default certificate store lookups to work on Windows platforms we will need to patch our boringssl implementation to support Windows style paths.

**Comment by lateralusX** [comment]
https://github.com/mono/boringssl/pull/19 should fix the CA trust root issue when using BTLS on Windows build. When approved, I will bump commit on Mono repro and investigate if we have tests covering this scenario for BTLS. Until then you can patch your local BTLS build and do local build and retry your scenario using patched library.

**Comment by lateralusX** [comment]
PR bumping Mono to use fixed boringssl implementation, https://github.com/mono/mono/pull/14435.

**Comment by npodbielski** [comment]
Is this already in master? After installing mono-complete (6.6.0.161-0xamarin7+debian10b1)
I still got this error:
`$ csharp -e 'new System.Net.WebClient ().DownloadString ("https://nuget.britishcouncil.org/nuget/Corporate/")'
System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /build/mono-6.6.0.161/external/boringssl/ssl/handshake_client.c:1132
  at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00048] in <dfe42095fd31410e95d8021f755c3557>:0 
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000da] in <dfe42095fd31410e95d8021f755c3557>:0 
  at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
  at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <dfe42095fd31410e95d8021f755c3557>:0 
  at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000fc] in <dfe42095fd31410e95d8021f755c3557>:0 
   --- End of inner exception stack trace ---
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00262] in <dfe42095fd31410e95d8021f755c3557>:0 
  at Mono.Net.Security.MonoTlsStream.CreateStream (System.Net.WebConnectionTunnel tunnel, System.Threading.CancellationToken cancellationToken) [0x00176] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x001ba] in <dfe42095fd31410e95d8021f755c3557>:0 
   --- End of inner exception stack trace ---
  at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x0021a] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00141] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.WebOperation.Run () [0x0009a] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00016] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream) [0x000e6] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x00061] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.WebClient.DownloadString (System.Uri address) [0x00011] in <dfe42095fd31410e95d8021f755c3557>:0 
  at System.Net.WebClient.DownloadString (System.String address) [0x00008] in <dfe42095fd31410e95d8021f755c3557>:0 
  at <InteractiveExpressionClass>.Host (System.Object& $retval) [0x00006] in <b6f72ca386774e3e9743c8d83d5286ee>:0 
  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object& result, System.Boolean& result_set) [0x00038] in <9690817f9cb549f68765c6e335257e1c>:0 
  at Mono.CSharpShell.Evaluate (System.String input) [0x00000] in <98106dc318924a49b374a5ae7325f846>:0 
`

**Comment by lateralusX** [comment]
This fix resolved issues on Windows where it didn't resolve any CA certificates at all due to the fixed issue. Since you are on a none Windows platform first thing to check is that the certificate chain returned by that web server can be resolved using the local trust store all the way to the root CA.

**Comment by npodbielski** [comment]
Thanks for info. 
I tried to do cert-sync and it do not work. Address opens up just fine in a browser. 
I tried to do use legacy provider but it fails too. 
I tried using cert-sync and it did not worked  either.
`certmgr -ssl https://somedomain.org` worked but verification still fail.
I think that Entrust CA is missing, but I think I added all of them and connection via mono still fails. Do you have some idea how to resolve this?

**Comment by lateralusX** [comment]
Maybe @baulig could assist since he has been working far more with the BTLS implementations on none Windows platforms.

**Comment by nkosi23** [comment]
Any idea here? Getting the same error as @npodbielski but on FreeBSD. 
cert-sync completes without error, but it is not possible to connect to the websites
