### ISSUE TITLE
Winform TreeView Image not showing

### ISSUE THREAD

**Issue by coryng** [mono/mono#17800]
## Steps to Reproduce

1. Simple winform application with treeview
2. Assign imagelist to treeview
3. Run on Ubuntu 18.04 and image icon on treeview nodes doesn't show

### Current Behavior
On Ubuntu, no icon image shown for treenode

### Expected Behavior
Icon image should be shown on treenode

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:
Mono 6.4.0.198.  (stable-bionic)
[mono.winforms.treview.imagelist.zip](https://github.com/mono/mono/files/3847762/mono.winforms.treview.imagelist.zip)

**Comment by filipnavara** [comment]
May be related to https://github.com/mono/mono/issues/17493.

**Comment by progszem** [comment]
I have the same issue with the same version of mono. I use a raspbian OS.

**Comment by filipnavara** [comment]
I gave this another try today but I was unable to reproduce the issue on my setup (WSL w/ Ubuntu 18.04, latest Mono and libgdiplus packages, VcXsrv as X server). The icons appear just fine, exactly the same as a native Windows version of the application.

**Comment by shadowng** [comment]
Unfortunately, I still have the same issue with latest Mono on a regular Linux box (now WSL)

**Comment by filipnavara** [comment]
Turns out this is a bug that I already fixed last year - https://github.com/mono/libgdiplus/commit/c98de971e5f453f50f898494b7791feb02302f62 (https://github.com/mono/libgdiplus/pull/604). The fix just newer made it to release.

**Comment by shadowng** [comment]
Any idea when this fix will be in the release?  Thanks

**Comment by akoeplinger** [comment]
It will be in a future libgdiplus 6.1 release

**Comment by shadowng** [comment]
I still have the same issue with latest Mono (6.8) on Ubuntu 20.04.  Unfortunately, it seems impossible to use older version of Mono on Ubuntu 20.04.  Any help is really appreciated.

**Comment by progszem** [comment]
> I still have the same issue with latest Mono (6.8) on Ubuntu 20.04. Unfortunately, it seems impossible to use older version of Mono on Ubuntu 20.04. Any help is really appreciated.

I still have, too. Raspbian 10, Mono 6.12.0.122.
![image](https://user-images.githubusercontent.com/54835714/125045480-54ac5700-e09d-11eb-8a84-1acfe619e709.png)

**Comment by rmfalco** [comment]
I have the same issue on Centos 7 mono 6.12.0.122. Any idea when this issue will be addressed?

thanks

**Comment by TeoMan** [comment]
This might be related to https://github.com/mono/mono/issues/17747

**Comment by filipnavara** [comment]
> This might be related to #17747

As stated [3 years ago](https://github.com/mono/mono/issues/17800#issuecomment-609074405), this bug was fixed in libgdiplus. New version was just never released and libgdiplus was effectively deprecated, just as Mono was (it lives on as MonoVM in dotnet/runtime, but not with the old class libraries like WinForms).
