### ISSUE TITLE
why max-heap-size was not considered to evaluate the next trigger size in GC algorithm

### ISSUE THREAD

**Issue by PaparaoG** [mono/mono#19791]
## Steps to Reproduce

1.  set max-heap-size to 60 mb
2. Enable GC debug parameter print-allowance to check trigger size.
3. GC will  be triggered based on computed trigger size. If computed trigger size goes beyond max-heap-size then GC won't be triggered which will result into **out of memory  or system crash** due to system reached its max-heap-size limit.

_**mono/sgen/sgen-memory-governor.c**_
refer to function 
```
static void sgen_memgov_calculate_minor_collection_allowance {
---
---
	major_collection_trigger_size = new_heap_size + allowance; 
// Looks like the algorithm was implemented by considering default heap size. It should have considered max-heap-size also to determine appropriate the trigger size, if it was set.
--
---
}
```

### Current Behavior

The next trigger size was computed based on new-heap-size and allowance. However it is not considering the max-heap-size set by the user because of which we are noticing the out of memory exception, it is mainly the computed trigger size was going beyond max-heap-size not triggering GC collection.
### Expected Behavior
If GC algorithm can considers the max-heap-size (if it was set) in evaluating the next trigger size then it will mitigate out of memory/ crash issues. 

I would like to know whether it is a bug or expected behavior.
## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by jbatt33** [comment]
I'm not sure if this is related, but I am seeing an issue where we are running out of memory with mono 6.4. We are able to create a test function that shouldn't leak memory, but does: 

In a thread we have the following loop, after about 20 minutes or so we see GC is no longer collecting as expected. 

> 
> for (int loopCnt = 0; loopCnt < 1000; loopCnt++)
> {
>  var myList = new List<string>();
>  Stopwatch stopwatch = new Stopwatch();
>  stopwatch.Start();
>  Random tRandom = new Random();
>  for (Int32 i = 0; i < 10000000; i++)
>  {
>    myList.Add(string.Format("HELLO-{0}-{1}", tRandom.Next(), tRandom.Next()));
>  }
>  stopwatch.Stop();               
>  myList.Clear();
>  myList = null;
>  GC.WaitForPendingFinalizers();
>  GC.Collect();
>  }
> 
>

**Comment by PaparaoG** [comment]
@jbatt33: Collect heapshot and verify the objects stranded in memory. Also enable mono gc parameter "print allowance" which helps to verify gc trigger size.

**Comment by jbatt33** [comment]
I'm still trying to narrow down a guaranteed way to reproduce the issue. I
will be getting heapshots and will enable this print. Thanks for your help.

**Comment by jbatt33** [comment]
Not too sure about what this debug is telling me, but from what I can see a lot of data is surviving each sweep.  Is this because my function didn't exit? 


```
-------------------Starting test ---------------------------
2020-06-02 08:51:19 Starting collection with heap size 18,744,992 bytes
2020-06-02 08:51:20 Surviving sweep: 31,201,632 bytes (1,703,936 major, 29,497,696 LOS)
2020-06-02 08:51:20 Allowance: 0 bytes
2020-06-02 08:51:20 Trigger size: 31,201,632 bytes
2020-06-02 08:51:20 Starting collection with heap size 64,756,080 bytes
2020-06-02 08:51:20 Surviving sweep: 119,273,808 bytes (1,703,936 major, 117,569,872 LOS)

--------------------Test Stopping-----------------------------

2020-06-02 08:52:29 Allowance: 368,554,204 bytes
2020-06-02 08:52:29 Trigger size: 1,679,010,556 bytes
2020-06-02 08:52:29 Starting collection with heap size 1,713,101,600 bytes
2020-06-02 08:52:29 Surviving sweep: 1,328,020,000 bytes (1,703,936 major, 1,326,316,064 LOS)
2020-06-02 08:52:29 Allowance: 437,174,465 bytes
2020-06-02 08:52:29 Trigger size: 1,765,194,465 bytes
2020-06-02 08:52:30 Starting collection with heap size 1,863,834,512 bytes
2020-06-02 08:52:31 Surviving sweep: 1,495,792,192 bytes (1,703,936 major, 1,494,088,256 LOS)


```
The program was simplified to the loop from above to only add a bunch of integers to the list. So we are not using any "complex" object. 

```
for (Int32 i = 0; i < 20000000; i++)
{
   myList.Add(i);
 }

```

Working to get heapshots, also I'm running this on Linux - ARM

```
Mono JIT compiler version 6.4.0.198 (tarball Thu May 21 20:37:44 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

```

**Comment by jbatt33** [comment]
From my testing things seem to be running a bit better when I pushed the collection populating loop to a new function... still gathering information.

**Comment by jbatt33** [comment]
Sorry this is taking so long to get the information... I just did five runs of the test and each time I got different results. 

Attached a chart showing the five different runs. The program is started new for each run. 

![Surving](https://user-images.githubusercontent.com/41477628/83555857-f2b61100-a4dc-11ea-8e2f-bf2f602c96d6.png)

**Comment by jbatt33** [comment]
Getting heap shots, but looking at this run, GC was working great, but then for whatever reason, the trigger size starts increasing.

[GC_Trigger_Increasing.txt](https://github.com/mono/mono/files/4719475/GC_Trigger_Increasing.txt)

**Comment by jbatt33** [comment]
I need to get some more heap information, but looking at these two heap captures, I can see that the Int32[]s are not all being deleted from memory. 
[FirstHdumps.zip](https://github.com/mono/mono/files/4719742/FirstHdumps.zip)

**Comment by BrzVlad** [comment]
@PaparaoG From mono manual : 
> Sets the maximum size of the heap. The size is specified in bytes and must be a power of two. The suffixes `k`, `m`  and  `g` can  be  used  to  specify kilo-, mega- and gigabytes, respectively. The limit is the sum of the nursery, major heap and large object heap. Once the limit is reached the application will receive OutOfMemoryExceptions when trying to  allocate. Not the full extent of memory set in max-heap-size could be available to satisfy a single allocation due to internal fragmentation. By default heap limits is disabled and the GC will try to use all available memory.

The trigger size shouldn't really exceed max-heap-size. If the GC doesn't have enough space for an allocation, it should trigger a collection and if still not enough space was freed in order to fulfill the allocation while keeping the heap size under max_heap_size it should just OOM.

@jbatt33 You seem to be investigating a dead end. Our GC is conservative with values in stack and regs which means some objects might survive for longer, even if you can tell in the code they will no longer be used. This means some objects might survive a loop iteration in your case, for a little longer. As long as the memory doesn't steadily increase over minutes / hours of running, this is no leak, just random variation due to pinning/unpinning of objects on the stack.

**Comment by jbatt33** [comment]
@BrzVlad  My issue is that I can't get GC to free up the objects that are no longer referenced. Since they are not freed the system runs out of memory.  I verified if I set the max heap size and the soft heap limit the program will throw a out of memory exception because GC refuses to free up objects that are no longer used in the application. 

I supplied the application with 600MB as the max and the soft limit was 500MB

**Comment by jbatt33** [comment]
@BrzVlad Just want to make sure I understand your comment. The issue I'm seeing is just because I'm not letting GC run enough cycles and that the test isn't really valid for real world usage of an application. Right?

**Comment by BrzVlad** [comment]
That is correct. While I can't see the exact implementation of this List container, in this small test you seem to be adding 20000000 objects, each with size of 24 bytes (16 bytes header + 4 bytes value + padding). This adds up to 480MB + internal list arrays kept alive by a single list reference. So you can imagine that if a single list object is left on the stack, the system will run out of memory.

There is really no good solution for this. In general, you would want to make sure that your application uses memory more efficiently, so you have more memory available in case you need it and. you don't depend on these GC details. If you have an idea of what objects are being kept alive (you could try out Xamarin.Profiler for example) you could attempt to help the GC by clearing the references to them. For example, in the above testcase, when clearing and disposing the list, you could zero all the entries in the arrays storing the object references. If you do this, even if the list reference happens to remain alive somewhere on the stack, it wouldn't matter because it no longer references millions of objects.

**Comment by jbatt33** [comment]
As an update, you are correct where GC is not collecting the items because GC doesn't run enough times. I modified the test to issue GC.Collect calls between the iterations and the system is able to run with out taking up the entire system's memory.

  This is good, but is there was a way to prevent the system from normally taking up all memory of the system without having to force GC to run.

**Comment by jbatt33** [comment]
I'll let @BrzVlad respond as well, but I believe we are ok here. 
I believe most of the GC issues observed are due to running on an ARM platform as well.

**Comment by SamMonoRT** [comment]
@BrzVlad @fanyang-mono - confirm this is not an issue anymore and close as appropriate.

**Comment by PaparaoG** [comment]
We used alternative to this so you please close the issue. However, still it requires improvement in algorithm.

Thanks,
Paparao





________________________________

**Comment by BrzVlad** [comment]
There are quite a few issues with OOM handling in mono. Looked a little bit at things that are wrong and added them to https://github.com/dotnet/runtime/issues/61095 for tracking
