### ISSUE TITLE
Mono embedded 'System.Console' threw an exception.

### ISSUE THREAD

**Issue by droyer57** [mono/mono#21061]
I'm writing an cpp application that embedded mono. I compiled mono 6.12.0.122 from tarball and link mono statically with cmake.
```cmake
set(LIBS "${PROJECT_SOURCE_DIR}/lib/libmonosgen-2.0.a" -lm -lrt -ldl -lz -pthread)
```
I had to add libz. It's not present in the pkgconfig module. Then I put everything of my install folder from my mono compilation to my root application. Then I set the `mono_set_dirs` properly. So I have :

```
app-root-folder/
  cpp-app
  mono/
    etc/
    lib/
    ...
```

```cpp
mono_set_dirs("<absolute_path>/mono/lib", "<absolute_path>/mono/etc");
```

It works fine but as soon as I write `Console.WriteLine()` on my assembly, it crash. <br>
Something strange that if I run directly my application with `F5` on my IDE (CLion), it works. It also works if I double click on the executable with my file explorer. But it doesn't if I run my application on the terminal or if I reproduce the exact command used by my IDE to launch my application. So maybe a env problem ? 

My assembly is correctly load, I can do staff on my C# function but I cannot use `Console.WriteLine()`. It seams that it failed to load some `.so` files.

What am I missing ? <br>
Does `mkbundle` is useful in my case ?

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**: 6.12.0.122

## Stacktrace

https://pastebin.com/uDUfyRan

**Comment by droyer57** [comment]
I just found the issue. It seams that `Console.WriteLine` doesn't like `TERM=rxvt-unicode-256color`. So I just write `unsetenv("TERM");` on my cpp application.

Is it normal to do this ?
Does `mkbundle` can pack my application and my assemblies into one application ?

**Comment by lambdageek** [comment]
> I just found the issue. It seams that `Console.WriteLine` doesn't like `TERM=rxvt-unicode-256color`. So I just write `unsetenv("TERM");` on my cpp application.
> 
> Is it normal to do this ?

No.  you cna try running with environment variables `MONO_LOG_LEVEL=debug` `MONO_LOG_MASK=dll` to see what native library it's trying to load.

Most likely it's libmono-native.so.  That library should be in the same directory as libmonosgen-2.0.so, in /usr/lib somewhere.  If you're moving libmonosgen-2.0.so you will need to adjust your LD_LIBRARY_PATH so that it can find mono-native.

> Does `mkbundle` can pack my application and my assemblies into one application ?

Yes, although it is primarily geared toward applications where the C# code is the main application, and native code (if there is any) is in a shared library that's loaded by the application.  If you main application is in C/C++, you will need to write some custom support for mkbundle.  See the `mkbundle(1)` manpage for the `--mono-api-struct-path` option

**Comment by droyer57** [comment]
I don't compile in dynamic but static. So I used the `libmonosgen-2.0.a` file. I prefer this way because people doesn't have to have mono in their machine.
But I noticed that I have no crash at all when I compiled in dynamic.

I found a similar issue : https://www.gog.com/forum/pyre/you_may_have_trouble_running_this_from_the_terminal_on_linux
Here is the log with `MONO_LOG_MASK=dll` : https://pastebin.com/LfRttxxk

At the moment, everything seems to work fine by removing `TERM`. I just set `mono_set_assemblies_path` by pointing to the `<exe_absolute_path>/mono/lib` folder. Godot (that use the mono runtime embedded) has bunch of `.so` file in `<godot>/GodotSharp/Mono/lib`. And without that it crash but in my case I don't need it. I have the feeling that I'm going to have a crash later because something is not set properly.

What do you think about that ?

**Comment by lambdageek** [comment]
> I don't compile in dynamic but static. So I used the `libmonosgen-2.0.a` file. I prefer this way because people doesn't have to have mono in their machine.
> But I noticed that I had no crash at all when I compiled in dynamic.

The managed class libraries depend on some of the dynamic libraries that come with Mono, libmono-native and libmonoSupportW, at least.  Some functionality might be broken without them.

> 
> I found a similar issue : https://www.gog.com/forum/pyre/you_may_have_trouble_running_this_from_the_terminal_on_linux

That's https://github.com/mono/mono/issues/6752

But it was fixed 3 years ago, any mono newer than 5.12 should work with the new terminfo format.


> Here is the log with `MONO_LOG_MASK=dll` : https://pastebin.com/LfRttxxk

Thanks.

> 
> At the moment, everything seems to work fine by removing `TERM`. I just set `mono_set_assemblies_path` by pointing to the `<exe_absolute_path>/mono/lib` folder. Godot (that use the mono runtime embedded) has bunch of `.so` file in `<godot>/GodotSharp/Mono/lib`. And without that it crash but in my case I don't need it. I have the feeling that I'm going to have a crash later because something is not set properly.

Yea the managed libraries depend on the native .so libs - for simple code it might not be obvious if things are broken, but there might be missing functionality.

You might also need to call `mono_set_config_dir` and point it at a directory that has a `mono/config` file.  (ie: if the directory is `/opt/p1` it iwll look in `/opt/p1/mono/config`).  And then in that file, add a `dllmap` like the one in `data/config` (make sure to replace `$mono_libdir` with the directory where the .so files are).

> What do you think about that ?

**Comment by droyer57** [comment]
I did this `mono_set_config_dir("<absolute_path>/mono/etc")`, replaced `$mono_libdir` by my lib path in the config file but it still doesn't work. The config file of Godot didn't change, `$mono_libdir` is still present.

Godot did [this](https://github.com/godotengine/godot/blob/master/modules/mono/mono_gd/gd_mono.cpp#L206) with the shared lib, so I tried to set the `PATH` env variable like this but it still doesn't work.
```cpp
setenv("PATH", "<absolute_path>/mono/lib", 0);
```

I exported a simple Godot project. I noticed that if I remove the `etc` folder or the `.so` files in the `lib` folder, it crash if I run the app with a terminal. But it won't crash if I run the app with my file explorer. So depend on the way you launch the app, these files are required or not.

In my case, the only way to make it work is to remove the `TERM` env variable. With this, if I run my application with `MONO_LOG_LEVEL=debug` `MONO_LOG_MASK=dll`, I see nothing relative to mono (maybe because there was no errors).
Here is the log with `MONO_LOG_MASK=all` and no errors : https://pastebin.com/SQqFxWk2

With this line `Mono: Config attempting to parse: './mono/etc/mono/config'.`, it seems that mono take the good config file.

**Comment by droyer57** [comment]
I tried something else with a Godot exported project, if I remove the `etc` folder or the `.so` files in the `lib` folder, it crash by launching with a terminal with this error : `'System.Console' threw an exception`. But if run this command
`TERM= ./<godot_project_exe>`, it works. So the fix that mention @lambdageek is probably in the `.so` files.

But in my case, I cannot tell the mono runtime to load the `.so` files present in `<root_folder>/mono/lib`. I tried to copy the exact `lib` and `etc` folder from a Godot exported project to my project, but no effect. So I think Godot tell in their code where are the `.so` files. I really think it was [there](https://github.com/godotengine/godot/blob/master/modules/mono/mono_gd/gd_mono.cpp#L206) but it didn't work on my code sadly.
