### ISSUE TITLE
Mono application (keepass) crashes whole desktop environment

### ISSUE THREAD

**Issue by InRiPa** [mono/mono#21625]
The following issue might be related to mono. That's why I opened this issue. 
Certain actions (one of them I can reproduce) result in the application crashing and with it the whole Gnome Desktop Environment.  
A reference to a ticket, raised in the keepass ticket system is [here](https://sourceforge.net/p/keepass/bugs/2227/).

## Steps to Reproduce

0. Opening Keepass
1. Opening an entry
Details menu appears (under URL, I got 127.0.0.1)
2. Highlighting the 127.0.0.1 and pressing ctrl+c to copy
3. pressing space and ctrl+v to paste
4. removing last character in line (here the '1')
5. pressing another number (e.g. 3)

### Current Behavior

The application and gnome-shell crashes.

### Expected Behavior

No crash at all.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

```
$ mono --version
Mono JIT compiler version 6.12.0 (makepkg/ed0788bf61f Sun Apr 24 04:25:18 PM UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

```
$ keepass --version
KeePass 2.51
Copyright © 2003-2022 Dominik Reichl
```

```
Arch Linux
Linux 6.2.1-arch1-1
```

```
$ gnome-shell --version
GNOME Shell 43.3
```

## Stacktrace

```
Feb 24 16:57:27 <pc_name> gnome-shell[1671]: Window manager warning: Window 0x2a07153 sets an MWM hint indicating it isn't resizable, but sets min size 104 x 1 and max size 652 x 711; this doesn't make much sense.
Feb 24 16:57:27 <pc_name> gnome-shell[1671]: Window manager warning: Window 0x2a07153 sets an MWM hint indicating it isn't resizable, but sets min size 104 x 1 and max size 652 x 711; this doesn't make much sense.
Feb 24 16:57:27 <pc_name> gnome-shell[1671]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a07153
Feb 24 16:57:27 <pc_name> gnome-shell[1671]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a07153
Feb 24 16:57:31 <pc_name> gnome-shell[1671]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a00061
Feb 24 16:57:32 <pc_name> gnome-shell[1671]: Window manager warning: Window 0x2a07377 sets an MWM hint indicating it isn't resizable, but sets min size 104 x 1 and max size 652 x 711; this doesn't make much sense.
Feb 24 16:57:32 <pc_name> gnome-shell[1671]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a07377
Feb 24 16:57:32 <pc_name> gnome-shell[1671]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a07377
Feb 24 16:57:37 <pc_name> keepass.desktop[12751]: System.NullReferenceException: Object reference not set to an instance of an object
Feb 24 16:57:37 <pc_name> keepass.desktop[12751]:   at System.Windows.Forms.Line.InsertString (System.Int32 pos, System.String s, System.Windows.Forms.LineTag tag) [0x000a8] in <c6f7ca72402d44ffad61bbfb1e840a0f>:0
Feb 24 16:57:37 <pc_name> keepass.desktop[12751]:   at System.Windows.Forms.Document.InsertCharAtCaret (System.Char ch, System.Boolean move_caret) [0x0001d] in <c6f7ca72402d44ffad61bbfb1e840a0f>:0
Feb 24 16:57:37 <pc_name> keepass.desktop[12751]:   at System.Windows.Forms.TextBoxBase.WndProc (System.Windows.Forms.Message& m) [0x0013c] in <c6f7ca72402d44ffad61bbfb1e840a0f>:0
Feb 24 16:57:37 <pc_name> keepass.desktop[12751]:   at System.Windows.Forms.TextBox.WndProc (System.Windows.Forms.Message& m) [0x0011c] in <c6f7ca72402d44ffad61bbfb1e840a0f>:0
Feb 24 16:57:37 <pc_name> keepass.desktop[12751]:   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <c6f7ca72402d44ffad61bbfb1e840a0f>:0
Feb 24 16:57:37 <pc_name> keepass.desktop[12751]:   at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <c6f7ca72402d44ffad61bbfb1e840a0f>:0
Feb 24 16:57:37 <pc_name> keepass.desktop[12751]:   at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <c6f7ca72402d44ffad61bbfb1e840a0f>:0
Feb 24 16:57:37 <pc_name> gnome-shell[1671]: **
Feb 24 16:57:37 <pc_name> gnome-shell[1671]: libmutter:ERROR:../mutter/src/x11/group.c:75:meta_group_new: assertion failed: (g_hash_table_lookup (x11_display->groups_by_leader, &group_leader) == NULL)
Feb 24 16:57:37 <pc_name> gnome-shell[1671]: Bail out! libmutter:ERROR:../mutter/src/x11/group.c:75:meta_group_new: assertion failed: (g_hash_table_lookup (x11_display->groups_by_leader, &group_leader) == NULL)
Feb 24 16:57:37 <pc_name> gnome-shell[1671]: == Stack trace for context 0x55f7c3311630 ==
Feb 24 16:57:37 <pc_name> systemd[1]: Started Process Core Dump (PID 31075/UID 0).
eb 24 16:57:38 <pc_name> systemd-coredump[31076]: [🡕] Process 1671 (gnome-shell) of user 1000 dumped core.

                                                 Stack trace of thread 1671:
                                                 #0  0x00007ff4ba8a08ec n/a (libc.so.6 + 0x878ec)
                                                 #1  0x00007ff4ba851ea8 raise (libc.so.6 + 0x38ea8)
                                                 #2  0x000055f7c247bae9 n/a (gnome-shell + 0x2ae9)
                                                 #3  0x00007ff4ba851f50 n/a (libc.so.6 + 0x38f50)
                                                 #4  0x00007ff4ba8a08ec n/a (libc.so.6 + 0x878ec)
                                                 #5  0x00007ff4ba851ea8 raise (libc.so.6 + 0x38ea8)
                                                 #6  0x00007ff4ba83b53d abort (libc.so.6 + 0x2253d)
                                                 #7  0x00007ff4bb91006a n/a (libglib-2.0.so.0 + 0x1d06a)
                                                 #8  0x00007ff4bb96ba90 g_assertion_message_expr (libglib-2.0.so.0 + 0x78a90)
                                                 #9  0x00007ff4bab239e8 n/a (libmutter-11.so.0 + 0x1239e8)
                                                 #10 0x00007ff4bab25511 meta_window_compute_group (libmutter-11.so.0 + 0x125511)
                                                 #11 0x00007ff4baaf4fb0 n/a (libmutter-11.so.0 + 0xf4fb0)
                                                 #12 0x00007ff4bab40277 n/a (libmutter-11.so.0 + 0x140277)
                                                 #13 0x00007ff4baae615c n/a (libmutter-11.so.0 + 0xe615c)
                                                 #14 0x00007ff4bab4b6a6 n/a (libmutter-11.so.0 + 0x14b6a6)
                                                 #15 0x00007ff4bab27acd n/a (libmutter-11.so.0 + 0x127acd)
                                                 #16 0x00007ff4bab2aba9 n/a (libmutter-11.so.0 + 0x12aba9)
                                                 #17 0x00007ff4ba7a386f n/a (libgdk-3.so.0 + 0x8386f)
                                                 #18 0x00007ff4ba7ab435 n/a (libgdk-3.so.0 + 0x8b435)
                                                 #19 0x00007ff4ba751029 gdk_display_get_event (libgdk-3.so.0 + 0x31029)
                                                 #20 0x00007ff4ba7ab7c8 n/a (libgdk-3.so.0 + 0x8b7c8)
                                                 #21 0x00007ff4bb94882b g_main_context_dispatch (libglib-2.0.so.0 + 0x5582b)
                                                 #22 0x00007ff4bb99fcc9 n/a (libglib-2.0.so.0 + 0xaccc9)
                                                 #23 0x00007ff4bb947d8f g_main_loop_run (libglib-2.0.so.0 + 0x54d8f)
                                                 #24 0x00007ff4baad0a6b meta_context_run_main_loop (libmutter-11.so.0 + 0xd0a6b)
                                                 #25 0x000055f7c247b48d n/a (gnome-shell + 0x248d)
                                                 #26 0x00007ff4ba83c790 n/a (libc.so.6 + 0x23790)
                                                 #27 0x00007ff4ba83c84a __libc_start_main (libc.so.6 + 0x2384a)
                                                 #28 0x000055f7c247b715 n/a (gnome-shell + 0x2715)

                                                 Stack trace of thread 1785:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff49fb0c49e n/a (iris_dri.so + 0x10c49e)
                                                 #3  0x00007ff49fabc86c n/a (iris_dri.so + 0xbc86c)
                                                 #4  0x00007ff49fb0c3cc n/a (iris_dri.so + 0x10c3cc)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1705:
                                                 #0  0x00007ff4ba9139df __poll (libc.so.6 + 0xfa9df)
                                                 #1  0x00007ff4bb99fc2f n/a (libglib-2.0.so.0 + 0xacc2f)
                                                 #2  0x00007ff4bb9470e2 g_main_context_iteration (libglib-2.0.so.0 + 0x540e2)
                                                 #3  0x00007ff4bb947132 n/a (libglib-2.0.so.0 + 0x54132)
                                                 #4  0x00007ff4bb975db5 n/a (libglib-2.0.so.0 + 0x82db5)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1786:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff49fb0c49e n/a (iris_dri.so + 0x10c49e)
                                                 #3  0x00007ff49fabc86c n/a (iris_dri.so + 0xbc86c)
                                                 #4  0x00007ff49fb0c3cc n/a (iris_dri.so + 0x10c3cc)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1708:
                                                 #0  0x00007ff4ba9139df __poll (libc.so.6 + 0xfa9df)
                                                 #1  0x00007ff4bb99fc2f n/a (libglib-2.0.so.0 + 0xacc2f)
                                                 #2  0x00007ff4bb947d8f g_main_loop_run (libglib-2.0.so.0 + 0x54d8f)
                                                 #3  0x00007ff4bbb3caec n/a (libgio-2.0.so.0 + 0x10aaec)
                                                 #4  0x00007ff4bb975db5 n/a (libglib-2.0.so.0 + 0x82db5)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1790:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff49fb0c49e n/a (iris_dri.so + 0x10c49e)
                                                 #3  0x00007ff49fabc86c n/a (iris_dri.so + 0xbc86c)
                                                 #4  0x00007ff49fb0c3cc n/a (iris_dri.so + 0x10c3cc)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1789:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff49fb0c49e n/a (iris_dri.so + 0x10c49e)
                                                 #3  0x00007ff49fabc86c n/a (iris_dri.so + 0xbc86c)
                                                 #4  0x00007ff49fb0c3cc n/a (iris_dri.so + 0x10c3cc)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1791:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff49fb0c49e n/a (iris_dri.so + 0x10c49e)
                                                 #3  0x00007ff49fabc86c n/a (iris_dri.so + 0xbc86c)
                                                 #4  0x00007ff49fb0c3cc n/a (iris_dri.so + 0x10c3cc)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1868:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff49fb0c49e n/a (iris_dri.so + 0x10c49e)
                                                 #3  0x00007ff49fabc86c n/a (iris_dri.so + 0xbc86c)
                                                 #4  0x00007ff49fb0c3cc n/a (iris_dri.so + 0x10c3cc)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 26635:
                                                 #0  0x00007ff4ba9190dd syscall (libc.so.6 + 0x1000dd)
                                                 #1  0x00007ff45b91a735 n/a (librsvg-2.so.2 + 0x51a735)
                                                 #2  0x00007ff45b920b97 n/a (librsvg-2.so.2 + 0x520b97)
                                                 #3  0x00007ff45b4e6d0b n/a (librsvg-2.so.2 + 0xe6d0b)
                                                 #4  0x00007ff45b4e66ef n/a (librsvg-2.so.2 + 0xe66ef)
                                                 #5  0x00007ff45b66ba04 n/a (librsvg-2.so.2 + 0x26ba04)
                                                 #6  0x00007ff45b6676e1 n/a (librsvg-2.so.2 + 0x2676e1)
                                                 #7  0x00007ff45b668504 n/a (librsvg-2.so.2 + 0x268504)
                                                 #8  0x00007ff45b91f4c3 n/a (librsvg-2.so.2 + 0x51f4c3)
                                                 #9  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #10 0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1788:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff49fb0c49e n/a (iris_dri.so + 0x10c49e)
                                                 #3  0x00007ff49fabc86c n/a (iris_dri.so + 0xbc86c)
                                                 #4  0x00007ff49fb0c3cc n/a (iris_dri.so + 0x10c3cc)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1787:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff49fb0c49e n/a (iris_dri.so + 0x10c49e)
                                                 #3  0x00007ff49fabc86c n/a (iris_dri.so + 0xbc86c)
                                                 #4  0x00007ff49fb0c3cc n/a (iris_dri.so + 0x10c3cc)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1866:
                                                 #0  0x00007ff4ba9139df __poll (libc.so.6 + 0xfa9df)
                                                 #1  0x00007ff4bb99fc2f n/a (libglib-2.0.so.0 + 0xacc2f)
                                                 #2  0x00007ff4bb9470e2 g_main_context_iteration (libglib-2.0.so.0 + 0x540e2)
                                                 #3  0x00007ff4b16b5fde n/a (libdconfsettings.so + 0x5fde)
                                                 #4  0x00007ff4bb975db5 n/a (libglib-2.0.so.0 + 0x82db5)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 26637:
                                                 #0  0x00007ff4ba9190dd syscall (libc.so.6 + 0x1000dd)
                                                 #1  0x00007ff45b91a735 n/a (librsvg-2.so.2 + 0x51a735)
                                                 #2  0x00007ff45b920b97 n/a (librsvg-2.so.2 + 0x520b97)
                                                 #3  0x00007ff45b4e6d0b n/a (librsvg-2.so.2 + 0xe6d0b)
                                                 #4  0x00007ff45b4e66ef n/a (librsvg-2.so.2 + 0xe66ef)
                                                 #5  0x00007ff45b66ba04 n/a (librsvg-2.so.2 + 0x26ba04)
                                                 #6  0x00007ff45b6676e1 n/a (librsvg-2.so.2 + 0x2676e1)
                                                 #7  0x00007ff45b668504 n/a (librsvg-2.so.2 + 0x268504)
                                                 #8  0x00007ff45b91f4c3 n/a (librsvg-2.so.2 + 0x51f4c3)
                                                 #9  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #10 0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 26636:
                                                 #0  0x00007ff4ba9190dd syscall (libc.so.6 + 0x1000dd)
                                                 #1  0x00007ff45b91a735 n/a (librsvg-2.so.2 + 0x51a735)
                                                 #2  0x00007ff45b920b97 n/a (librsvg-2.so.2 + 0x520b97)
                                                 #3  0x00007ff45b4e6d0b n/a (librsvg-2.so.2 + 0xe6d0b)
                                                 #4  0x00007ff45b4e66ef n/a (librsvg-2.so.2 + 0xe66ef)
                                                 #5  0x00007ff45b66ba04 n/a (librsvg-2.so.2 + 0x26ba04)
                                                 #6  0x00007ff45b6676e1 n/a (librsvg-2.so.2 + 0x2676e1)
                                                 #7  0x00007ff45b668504 n/a (librsvg-2.so.2 + 0x268504)
                                                 #8  0x00007ff45b91f4c3 n/a (librsvg-2.so.2 + 0x51f4c3)
                                                 #9  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #10 0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1943:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff4b91965a1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-102.so + 0x15965a1)
                                                 #3  0x00007ff4b91964a2 n/a (libmozjs-102.so + 0x15964a2)
                                                 #4  0x00007ff4b934783e n/a (libmozjs-102.so + 0x174783e)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1946:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff4b91965a1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-102.so + 0x15965a1)
                                                 #3  0x00007ff4b91964a2 n/a (libmozjs-102.so + 0x15964a2)
                                                 #4  0x00007ff4b934783e n/a (libmozjs-102.so + 0x174783e)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1871:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff49fb0c49e n/a (iris_dri.so + 0x10c49e)
                                                 #3  0x00007ff49fabc86c n/a (iris_dri.so + 0xbc86c)
                                                 #4  0x00007ff49fb0c3cc n/a (iris_dri.so + 0x10c3cc)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 26639:
                                                 #0  0x00007ff4ba9190dd syscall (libc.so.6 + 0x1000dd)
                                                 #1  0x00007ff45b91a735 n/a (librsvg-2.so.2 + 0x51a735)
                                                 #2  0x00007ff45b920b97 n/a (librsvg-2.so.2 + 0x520b97)
                                                 #3  0x00007ff45b4e6d0b n/a (librsvg-2.so.2 + 0xe6d0b)
                                                 #4  0x00007ff45b4e66ef n/a (librsvg-2.so.2 + 0xe66ef)
                                                 #5  0x00007ff45b66ba04 n/a (librsvg-2.so.2 + 0x26ba04)
                                                 #6  0x00007ff45b6676e1 n/a (librsvg-2.so.2 + 0x2676e1)
                                                 #7  0x00007ff45b668504 n/a (librsvg-2.so.2 + 0x268504)
                                                 #8  0x00007ff45b91f4c3 n/a (librsvg-2.so.2 + 0x51f4c3)
                                                 #9  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #10 0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 26643:
                                                 #0  0x00007ff4ba9190dd syscall (libc.so.6 + 0x1000dd)
                                                 #1  0x00007ff45b91a735 n/a (librsvg-2.so.2 + 0x51a735)
                                                 #2  0x00007ff45b920b97 n/a (librsvg-2.so.2 + 0x520b97)
                                                 #3  0x00007ff45b4e6d0b n/a (librsvg-2.so.2 + 0xe6d0b)
                                                 #4  0x00007ff45b4e66ef n/a (librsvg-2.so.2 + 0xe66ef)
                                                 #5  0x00007ff45b66ba04 n/a (librsvg-2.so.2 + 0x26ba04)
                                                 #6  0x00007ff45b6676e1 n/a (librsvg-2.so.2 + 0x2676e1)
                                                 #7  0x00007ff45b668504 n/a (librsvg-2.so.2 + 0x268504)
                                                 #8  0x00007ff45b91f4c3 n/a (librsvg-2.so.2 + 0x51f4c3)
                                                 #9  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #10 0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 26634:
                                                 #0  0x00007ff4ba9190dd syscall (libc.so.6 + 0x1000dd)
                                                 #1  0x00007ff45b91a735 n/a (librsvg-2.so.2 + 0x51a735)
                                                 #2  0x00007ff45b920b97 n/a (librsvg-2.so.2 + 0x520b97)
                                                 #3  0x00007ff45b4e6d0b n/a (librsvg-2.so.2 + 0xe6d0b)
                                                 #4  0x00007ff45b4e66ef n/a (librsvg-2.so.2 + 0xe66ef)
                                                 #5  0x00007ff45b66ba04 n/a (librsvg-2.so.2 + 0x26ba04)
                                                 #6  0x00007ff45b6676e1 n/a (librsvg-2.so.2 + 0x2676e1)
                                                 #7  0x00007ff45b668504 n/a (librsvg-2.so.2 + 0x268504)
                                                 #8  0x00007ff45b91f4c3 n/a (librsvg-2.so.2 + 0x51f4c3)
                                                 #9  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #10 0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1948:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff4b91965a1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-102.so + 0x15965a1)
                                                 #3  0x00007ff4b91964a2 n/a (libmozjs-102.so + 0x15964a2)
                                                 #4  0x00007ff4b934783e n/a (libmozjs-102.so + 0x174783e)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1949:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff4b91965a1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-102.so + 0x15965a1)
                                                 #3  0x00007ff4b91964a2 n/a (libmozjs-102.so + 0x15964a2)
                                                 #4  0x00007ff4b934783e n/a (libmozjs-102.so + 0x174783e)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1944:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff4b91965a1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-102.so + 0x15965a1)
                                                 #3  0x00007ff4b91964a2 n/a (libmozjs-102.so + 0x15964a2)
                                                 #4  0x00007ff4b934783e n/a (libmozjs-102.so + 0x174783e)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1950:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff4b91965a1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-102.so + 0x15965a1)
                                                 #3  0x00007ff4b91964a2 n/a (libmozjs-102.so + 0x15964a2)
                                                 #4  0x00007ff4b934783e n/a (libmozjs-102.so + 0x174783e)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 26640:
                                                 #0  0x00007ff4ba9190dd syscall (libc.so.6 + 0x1000dd)
                                                 #1  0x00007ff45b91a735 n/a (librsvg-2.so.2 + 0x51a735)
                                                 #2  0x00007ff45b920b97 n/a (librsvg-2.so.2 + 0x520b97)
                                                 #3  0x00007ff45b4e6d0b n/a (librsvg-2.so.2 + 0xe6d0b)
                                                 #4  0x00007ff45b4e66ef n/a (librsvg-2.so.2 + 0xe66ef)
                                                 #5  0x00007ff45b66ba04 n/a (librsvg-2.so.2 + 0x26ba04)
                                                 #6  0x00007ff45b6676e1 n/a (librsvg-2.so.2 + 0x2676e1)
                                                 #7  0x00007ff45b668504 n/a (librsvg-2.so.2 + 0x268504)
                                                 #8  0x00007ff45b91f4c3 n/a (librsvg-2.so.2 + 0x51f4c3)
                                                 #9  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #10 0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 26641:
                                                 #0  0x00007ff4ba9190dd syscall (libc.so.6 + 0x1000dd)
                                                 #1  0x00007ff45b91a735 n/a (librsvg-2.so.2 + 0x51a735)
                                                 #2  0x00007ff45b920b97 n/a (librsvg-2.so.2 + 0x520b97)
                                                 #3  0x00007ff45b4e6d0b n/a (librsvg-2.so.2 + 0xe6d0b)
                                                 #4  0x00007ff45b4e66ef n/a (librsvg-2.so.2 + 0xe66ef)
                                                 #5  0x00007ff45b66ba04 n/a (librsvg-2.so.2 + 0x26ba04)
                                                 #6  0x00007ff45b6676e1 n/a (librsvg-2.so.2 + 0x2676e1)
                                                 #7  0x00007ff45b668504 n/a (librsvg-2.so.2 + 0x268504)
                                                 #8  0x00007ff45b91f4c3 n/a (librsvg-2.so.2 + 0x51f4c3)
                                                 #9  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #10 0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1872:
                                                 #0  0x00007ff4ba9139df __poll (libc.so.6 + 0xfa9df)
                                                 #1  0x00007ff4bb99fc2f n/a (libglib-2.0.so.0 + 0xacc2f)
                                                 #2  0x00007ff4bb947d8f g_main_loop_run (libglib-2.0.so.0 + 0x54d8f)
                                                 #3  0x00007ff4babd18f1 n/a (libmutter-11.so.0 + 0x1d18f1)
                                                 #4  0x00007ff4bb975db5 n/a (libglib-2.0.so.0 + 0x82db5)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1945:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff4b91965a1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-102.so + 0x15965a1)
                                                 #3  0x00007ff4b91964a2 n/a (libmozjs-102.so + 0x15964a2)
                                                 #4  0x00007ff4b934783e n/a (libmozjs-102.so + 0x174783e)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 1947:
                                                 #0  0x00007ff4ba89b766 n/a (libc.so.6 + 0x82766)
                                                 #1  0x00007ff4ba89df90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                 #2  0x00007ff4b91965a1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-102.so + 0x15965a1)
                                                 #3  0x00007ff4b91964a2 n/a (libmozjs-102.so + 0x15964a2)
                                                 #4  0x00007ff4b934783e n/a (libmozjs-102.so + 0x174783e)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 2716:
                                                 #0  0x00007ff4ba9139df __poll (libc.so.6 + 0xfa9df)
                                                 #1  0x00007ff45b2a78c7 n/a (libpulse.so.0 + 0x338c7)
                                                 #2  0x00007ff45b29146c pa_mainloop_poll (libpulse.so.0 + 0x1d46c)
                                                 #3  0x00007ff45b29b42c pa_mainloop_iterate (libpulse.so.0 + 0x2742c)
                                                 #4  0x00007ff45b29b4e1 pa_mainloop_run (libpulse.so.0 + 0x274e1)
                                                 #5  0x00007ff45b2abc02 n/a (libpulse.so.0 + 0x37c02)
                                                 #6  0x00007ff45b248c57 n/a (libpulsecommon-16.1.so + 0x5bc57)
                                                 #7  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #8  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)

                                                 Stack trace of thread 31074:
                                                 #0  0x00007ff4ba9190dd syscall (libc.so.6 + 0x1000dd)
                                                 #1  0x00007ff4bb9993e3 g_cond_wait_until (libglib-2.0.so.0 + 0xa63e3)
                                                 #2  0x00007ff4bb916893 n/a (libglib-2.0.so.0 + 0x23893)
                                                 #3  0x00007ff4bb97b67b n/a (libglib-2.0.so.0 + 0x8867b)
                                                 #4  0x00007ff4bb975db5 n/a (libglib-2.0.so.0 + 0x82db5)
                                                 #5  0x00007ff4ba89ebb5 n/a (libc.so.6 + 0x85bb5)
                                                 #6  0x00007ff4ba920d90 n/a (libc.so.6 + 0x107d90)
                                                 ELF object binary architecture: AMD x86-64
Feb 24 16:57:38 <pc_name> systemd[1]: systemd-coredump@5-31075-0.service: Deactivated successfully.
Feb 24 16:57:38 <pc_name> gnome-calendar[4525]: Error reading events from display: Broken pipe
Feb 24 16:57:38 <pc_name> gnome-shell[3191]: (EE) failed to read Wayland events: Connection reset by peer
Feb 24 16:57:38 <pc_name> org.gnome.Evolution.desktop[2777]: Gdk-Message: 16:57:38.283: Error reading events from display: Broken pipe
Feb 24 16:57:38 <pc_name> gsd-media-keys[2106]: Error reading events from display: Broken pipe
Feb 24 16:57:38 <pc_name> org.gnome.Evolution.desktop[2613]: Gdk-Message: 16:57:38.283: Error reading events from display: Broken pipe
Feb 24 16:57:38 <pc_name> xdg-desktop-por[2344]: Error reading events from display: Broken pipe
Feb 24 16:57:38 <pc_name> org.gnome.Evolution.desktop[2793]: Gdk-Message: 16:57:38.284: Error reading events from display: Broken pipe
Feb 24 16:57:38 <pc_name> gsd-power[2109]: Error reading events from display: Broken pipe
Feb 24 16:57:38 <pc_name> org.gnome.Evolution.desktop[2762]: Gdk-Message: 16:57:38.284: Error reading events from display: Broken pipe
Feb 24 16:57:38 <pc_name> tilix[3702]: Error reading events from display: Connection reset by peer
```

**Comment by HinTak** [comment]
Do you have an unusual locale and/or use any XIM related functionality on your desktop? There is (as far as I know, still a problem) an old bug which needs setting `MONO_WINGFORMS_XIM_STYLE=disabled` to work around. It is bug 28047 in the old xamarin bugzilla.

**Comment by twk1989** [comment]
Hi, I encounter the same issue in my winform application. The step to reproduce is the same:
1. Copy text.
2. put space first
3. paste the text
4. backspace to delete some text
5. type something

This issue is happen in mono version 6.12.0.182, not in 6.8.0.123. Please refer to the videos in the zip.
[reproduce.zip](https://github.com/mono/mono/files/13366880/reproduce.zip)

Is there any solution/workaround for this? This is the exception:

System.NullReferenceException: Object reference not set to an instance of an object
  at System.Windows.Forms.Line.InsertString (System.Int32 pos, System.String s, System.Windows.Forms.LineTag tag) [0x000a8] in <74a5b17e349b4b8cac2d760234361fdf>:0 
  at System.Windows.Forms.Document.InsertCharAtCaret (System.Char ch, System.Boolean move_caret) [0x0001d] in <74a5b17e349b4b8cac2d760234361fdf>:0 
  at System.Windows.Forms.TextBoxBase.WndProc (System.Windows.Forms.Message& m) [0x0013c] in <74a5b17e349b4b8cac2d760234361fdf>:0 
  at System.Windows.Forms.TextBox.WndProc (System.Windows.Forms.Message& m) [0x0011c] in <74a5b17e349b4b8cac2d760234361fdf>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <74a5b17e349b4b8cac2d760234361fdf>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <74a5b17e349b4b8cac2d760234361fdf>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <74a5b17e349b4b8cac2d760234361fdf>:0

**Comment by InRiPa** [comment]
I can reproduce it still as well. I thought it was fixed, but if I follow my insructions (pressing space and pasting with removing a character ) it crashes again.

```bash
mono --version
Mono JIT compiler version 6.12.0 (makepkg/d9a6e8710b3 Thu Aug 31 10:53:20 UTC 2023)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

```bash
keepass --version
KeePass 2.54
Copyright © 2003-2023 Dominik Reichl
```

**Comment by HinTak** [comment]
I shall ask again - what locale your computer is set in, and what input methods you have, and have you tried disabling XIM ?

**Comment by InRiPa** [comment]
Sorry for not responding on that matter.
```bash
$>cat /etc/locale.conf 
LANG=en_US.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
```
Running with:
`$>MONO_WINGFORMS_XIM_STYLE=disabled keepass`
results in the same behavior. Was this meant to be a env variable?

**Comment by HinTak** [comment]
Yes,`MONO_WINGFORMS_XIM_STYLE=disabled` is an environment variable and us known to work around some crashes related to internationalisation and non-english locales.

**Comment by twk1989** [comment]
I assume it is MONO_WINFORMS_XIM_STYLE=disabled. Tried this and the exception still persist. The question here is using version 6.8.0.123 does not have this issue, it is happening only in 6.12.0.182. Please check my video in my previous comment.
