### ISSUE TITLE
Graphics DrawImage looks wrong on Linux when using SetColorKey

### ISSUE THREAD

**Issue by Harteex** [mono/mono#8514]
## Steps to Reproduce

To reproduce, use the following test project:
Get the project/solution [MonoColorBug.zip](https://github.com/mono/mono/files/1960561/MonoColorBug.zip) or create a new windows forms project, add a picture box, setup the form Shown event and [use the following code](https://pastebin.com/jxCSKs58).

### Current Behavior

On Windows with .NET it looks like it should, like this:
![dotnet-windows-c](https://user-images.githubusercontent.com/815152/39427855-96d0c17a-4c85-11e8-8976-457663813ba7.png)

But on linux with Mono, it instead looks like this:
![mono-linux-c](https://user-images.githubusercontent.com/815152/39427862-a03f1d9c-4c85-11e8-8871-51504c977643.png)

However, when using Wine and the Wine Mono package, it looks correct like it does on Windows with .NET.

### Expected Behavior

I expect it to look on Linux with Mono as it does with .NET on Windows.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

(I haven't tested Mac)

**Version Used**:

Tested versions: 4.2.1 and 5.10.1

The Wine-Mono version (where everything looked correct) was version 4.7.1-1 (Wine version 3.7).

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by Harteex** [comment]
More observations and workaround:

The same problem occurs when loading a bitmap, calling MakeTransparent on it and then drawing with Graphics. 

Consider an image with magenta as its transparent color. After the MakeTransparent call, I noticed that on mono, a transparent pixel was 00FF00FF (magenta with zero alpha), while on dot net, it was 00000000.

I tested to set these pixels to 00000000 manually with SetPixel, which gave the desired behaviour on Mono. So a workaround is to not use SetColorKey, but set the color instead to transparent black.

But even when manually setting the pixels to 00FF00FF it works on dot net, so it should work on Mono as well.

**Comment by danboid** [comment]
I think I may have encountered this same bug but if I have I don't think mine is related to SetColorKey or MakeTransparent because the program I'm using doesn't call either but it does use DrawImage.

There is a problem with the drawing of alpha channels when running the WIP 02 version of Kroah's C# remake of Speedball 2 under monodevelop, which you can see in the attached screenshot. I have built the code under Windows VS 2017 and there are no pink backgrounds surrounding the sprites, nor do I see this issue when I run the SB WIP 02 binary under wine (or real Windows) so it seems to be a mono-specific issue.

http://bringerp.free.fr/RE/Speedball2/remake.php5

![screenshot_2018-09-14_13-39-22](https://user-images.githubusercontent.com/1429783/45551351-86394100-b825-11e8-8849-48cdc4716b2a.png)

**Comment by filipnavara** [comment]
I am almost positive that this was already addressed with a bug fix in the `libgdiplus` library. However it would require someone to download the latest GIT, compile and test it with the applications.

**Comment by danboid** [comment]
Hi filip!

I forgot to mention that I was (am) seeing this issue using the latest monodevelop for Ubuntu 18.04 as installed from the official PPA https://www.monodevelop.com/download/

Today I tried again but with a fully updated Arch - same issue so I updated libgdiplus to the latest git version and the problem persists. I'll have to check their bug tracker to see if they're aware of this.

**Comment by filipnavara** [comment]
Thanks for testing it. If the problem persists even with libgdiplus from GIT I will look into it. It's likely to take a few days to get to it though.

**Comment by danboid** [comment]
https://github.com/mono/libgdiplus/issues/491

**Comment by danboid** [comment]
Hi Filip

Thanks for looking into this! When you say "the code applies..." what are you referring to? libgdiplus? Will this be easy to fix?

**Comment by filipnavara** [comment]
libgdiplus, fix is in the works.

**Comment by StoddardOXC** [comment]
Another data point: DrawImage with transparency (left- mono, right - wine):

![drawimagebug](https://user-images.githubusercontent.com/20479892/45926256-7dcdbe00-bf29-11e8-8d6d-cf442093a8aa.png)

code: https://github.com/kevL/OpenXCOM.Tools

**Comment by peteryangthinkgeo** [comment]
What's the status of the issue?

**Comment by StoddardOXC** [comment]
Any news?

**Comment by sancheolz** [comment]
In latest mono and libgdiplus from master still reproducible

**Comment by filipnavara** [comment]
@sancheolz Thanks for testing it, I will try to reproduce it on my machine tonight and look for the cause.

**Comment by filipnavara** [comment]
The issue is here:

https://github.com/mono/libgdiplus/blob/aff49ac7b568b5e12b244ebb304bc068fecf51d1/src/imageattributes.c#L350-L352

It compares a color that has alpha channel masked out with the key values that don't have it masked out. I have to verify what the proper behavior is (masking both vs masking none) and then I'll submit a pull request to fix it.
