### ISSUE TITLE
AppleTlsContext.EvaluateTrust Doesn't seem to respect ServerCertificateValidationCallback

### ISSUE THREAD

**Issue by TheAngryByrd** [mono/mono#8660]
## Steps to Reproduce

1. Make a websocket server with a self signed certificate 
2. Try connecting using a ClientWebSocket
3. 

### Current Behavior

The client websocket fails to connect due to the cert not being trusted. Setting `System.Net.ServicePointManager.ServerCertificateValidationCallback` to accept all doesn't seem to affect this.

### Expected Behavior

Allowing `System.Net.ServicePointManager.ServerCertificateValidationCallback` to possibly allow for trust.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
mono -V
Mono JIT compiler version 5.8.0.108 (2017-10/9aa78573ee2 Wed Jan 10 04:30:03 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```

## Stacktrace

```
Unexpected error: System.AggregateException: One or more errors occurred. ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Security.Interface.TlsException: CertificateUnknown
  at Mono.AppleTls.AppleTlsContext.EvaluateTrust () [0x000d1] in <04fdc8acaa5e466bb267a3960bdb1f37>:0
  at Mono.AppleTls.AppleTlsContext.RequirePeerTrust () [0x00008] in <04fdc8acaa5e466bb267a3960bdb1f37>:0
  at Mono.AppleTls.AppleTlsContext.ProcessHandshake () [0x00046] in <04fdc8acaa5e466bb267a3960bdb1f37>:0
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status) [0x0003e] in <04fdc8acaa5e466bb267a3960bdb1f37>:0
  at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus)
  at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <04fdc8acaa5e466bb267a3960bdb1f37>:0
  at Mono.Net.Security.AsyncProtocolRequest+<ProcessOperation>d__24.MoveNext () [0x000ff] in <04fdc8acaa5e466bb267a3960bdb1f37>:0
```

**Comment by baulig** [comment]
It is certainly possible that we did not hook up the callback.  I have some other stuff in that area on my short-term TODO list, so I'll have a look at it.

**Comment by nealef** [comment]
Any progress on this issue? We can reproduce if you need additional information.

**Comment by nealef** [comment]
I have been looking at this and have come up with a solution that works for my test case but I am not sure if it is robust enough to be a general solution. I have implemented the ChainStatus property for Btls. When we execute the certificate verification callback we just don't test for success and set status11. Now we get the error (if any) and map the error code to those defined by ChainStatusFlags and add it to a list of X509ChainStatus objects for that chain. Now when get_ChainStatus is called we convert that list to an array of X509ChainStatus and return it. 

I will generate a PR so that those better familiar with the architecture can critique. Hopefully we can come up with something acceptable.

**Comment by nealef** [comment]
PR #10134 raised

**Comment by jiria** [comment]
I can see this still reproing and it completely breaks usage of mono for me. I am using Docker and mono:6.6 and mono:6.8 are ignoring the validation callback and just failing to verify the certificates. mono:5 does not ignore the callback, however it is returning incorrect values when compared with .netfx, thus making the code unportable. The same application code works flawlessly on .netfx.

**Comment by captainjono** [comment]
I have just attached some code to a to Xamarin.Mac project and i am hitting this error using ClientWebSocket. Works fine on windows platforms - can confirm ServicePointManager.ServerCertificateValidationCallback isnt ever interrogated in the connection attempt which will be the reason for the failure.

@baulig

**Comment by Vasile-Peste** [comment]
Hello, this problem still persists after all this years, it's possible to address it?
