### ISSUE TITLE
RestSharp breaks when upgrading mono from 5.10 to 5.12

### ISSUE THREAD

**Issue by pettfre** [mono/mono#9511]
Whenever RestSharp gets a response containing anything else other than a 2xx code, the response model returned from the method "Execute" contains all default values and an exception when run under mono 5.12.0.226 on Linux as described below. However, when running the same application under mono 5.12.0.226 on Windows or under mono 5.10.1.47 on Linux, everything works as intended. I also tried running the application using 5.14.0.161 on Linux but that failed the same way as when using 5.12.0.226.

I've provided a zip file with the smallest application I could manage to build showing the bug, two Dockerfiles with the different mono versions as well as the stacktrace found in the response provided by RestSharp.

## Steps to Reproduce

1. unzip mono-restsharp-test.zip
2. cd mono-restsharp-test
3. docker build -f Dockerfile-5.10.1.47 -t mono-restsharp-test:5.10.1.47 .
4. docker build -f Dockerfile-5.12.0.226 -t mono-restsharp-test:5.12.0.226 .
5. docker run --name wiremock -d -p 8080:8080 rodolpheche/wiremock
6. docker run --network host mono-restsharp-test:5.10.1.47
7. docker run --network host mono-restsharp-test:5.12.0.226

[mono-restsharp-test.zip](https://github.com/mono/mono/files/2185273/mono-restsharp-test.zip)

### Current Behavior

Step 7 above returns:
```
Status Code: 0
```

### Expected Behavior

Step 6 above returns:
```
Status Code: InternalServerError
```

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

5.10.1.47
5.12.0.226
5.14.0.161

## Stacktrace

```
Exception:
Error getting response stream (ReadAsync): ReceiveFailure Value cannot be null.
Parameter name: src
  at System.Net.WebConnectionStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00077] in <fc308f916aec4e4283e0c1d4b761760a>:0 
  at RestSharp.Extensions.MiscExtensions.ReadAsBytes (System.IO.Stream input) [0x0001f] in <fbc1773820994329b6ad5765a24d59a5>:0 
  at RestSharp.Http.ProcessResponseStream (System.IO.Stream webResponseStream, RestSharp.HttpResponse response) [0x0000e] in <fbc1773820994329b6ad5765a24d59a5>:0 
  at RestSharp.Http.ExtractResponseData (RestSharp.HttpResponse response, System.Net.HttpWebResponse webResponse) [0x0004c] in <fbc1773820994329b6ad5765a24d59a5>:0 
  at RestSharp.Http.GetResponse (System.Net.HttpWebRequest request) [0x00017] in <fbc1773820994329b6ad5765a24d59a5>:0 

Inner Exception:
Value cannot be null.
Parameter name: src
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000ba] in <fc308f916aec4e4283e0c1d4b761760a>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0 
  at System.Net.WebResponseStream+<ReadAsync>d__48.MoveNext () [0x00253] in <fc308f916aec4e4283e0c1d4b761760a>:0 
```

**Comment by marek-safar** [comment]
@baulig could you look into this issue?

**Comment by AmrAlSayed0** [comment]
Is there a work around to this problem? On Android, what version of Xamarin.Forms do I have to use to avoid using mono 5.12 and use mono 5.10?

**Comment by marek-safar** [comment]
@baulig please check this again, looks like regression from async rewrite

**Comment by baulig** [comment]
I debugged this and it's working just fine - both with current master and the most ancient version of Mono that I could find on my computer (which is 5.16.0.119).

However, there might be a misunderstanding between what you expect from RestSharp and what it actually does when it comes to errors since you're only printing `IRestResponse.StatusCode` in your test case.

I looked at RestSharp's source code and `IRestResponse.StatusCode` is only set if the request actually produced a response (so it will be zero on connection refused, for instance).  However,  `IRestResponse.ResponseStatus` is always set to `Error` when something went wrong.

**Comment by KCow** [comment]
Hello, I can confirm I have also been getting this since doing a Visual Studio upgrade on my Xamarin Forms project targetted at Android 8.1, a lot got updated at once so can't be sure whether it was the Mono upgrade specifically that caused this. But on the response from an ExecuteAsync I am now always seeing the "Error getting response stream" error with a Status Code of 0 even though the back end supplied a 401 HTTP code, see screenshot for the RestResponse.

![restsharp_401_wrong_error](https://user-images.githubusercontent.com/8123742/45083696-681c6400-b0f4-11e8-9e93-ddc55cf4ecd6.png)

I need to find a workaround fairly quick, I just need to understand why this is occurring so I know what to revert.

**Comment by AmrAlSayed0** [comment]
If possible, can this issue take priority? All the errors codes sent from our server is not received and it is breaking all kinds of functionality in our app. I have tried a lot but didn't find a workaround yet.

**Comment by marek-safar** [comment]
This should be addressed by #9511 as well

**Comment by SteveInCO** [comment]
For a workaround, see https://stackoverflow.com/questions/52402634

**Comment by lewurm** [comment]
@marek-safar your last comment links to this issue

**Comment by molidestroyer** [comment]
I'm still having this issue, and the solution specified here it's not working for me. HELP!

**Comment by steffenh13** [comment]
For the guys using Xamarin encountering this problem:
The last confirmed working Xamarin.iOS version is 11.10 using Mono 5.10 ([download from Xamarin Jenkins](https://jenkins.xamarin.com/view/Xamarin.MaciOS/job/macios-mac-d15-7/)) and for Xamarin.Android the version 8.3 seems to be working ([download from Xamarin Jenkins](https://jenkins.xamarin.com/view/Xamarin.Android/job/xamarin-android-builds-d15-7/)).

We have to wait on Xamarin to get current versions including the fixed Mono version, the current Xamarin previews don't have the fix yet.

**Comment by AmrAlSayed0** [comment]
@steffenh13 Will this cause any problems when using API 27/28 Build SDK? Do I have to downgrade? If I have to downgrade, won't this cause problems with Xamarin.Forms which is built using a newer version (ie. newer versions of support libraries) ?

Excuse me if I am misunderstanding something here. I don't fully understand how Xamarin.Android building work.

**Comment by steffenh13** [comment]
@AmrAlSayed0
It might cause some problems if you are dependent on Android SDK 28 or iOS 12 SDK and you might need to downgrade to use this fix.
For me it didn't cause any problems as the projects still use 27 as target and we don't have yet any iOS 12 dependent stuff.

I also didn't test this on Visual Studio for Windows yet, only on Visual Studio for Mac, as we need both iOS and Android anyways.

**Comment by JLS-LDang** [comment]
Chiming in to mention that downgrading mono did solve my problem for macs for now.
I just went to here and download the install the Visual Studio Channel version 15.10.1: 
https://www.mono-project.com/download/stable/#download-mac

I created unit tests to make several calls using RestSharp and noticed some of them failing after updating Xamarin Studio for Mac and here are the things I noticed:  
- Did not have any issues on Windows (all unit test passed), just running tests on Macs had failures
- 20% of my unit tests consistently failed which were mainly pointing to our public API
- Status Code 0 Timeout was what I been seeing from all the responses that failed
- When testing the call on Safari, it returned the correct data (so I ruled out network issue here)

**Comment by amolsarmalkar** [comment]
Hi all,
Our solution consists of 3 projects .

One is shared project whose dll is referenced in iOS project as well as Android. In shared project we use Rest client with RestSharp library version 105.2.3. However the api fails if token is expired. We used ExecuteTaskAsync function of Restclient and it is GET request. ExecuteTaskAsync generates web exception.

This code statement that generates exception
var response = await client.ExecuteTaskAsync(request);

The web exception it generates is : Error getting response stream (ReadAsync): ReceiveFailure Value cannot be null.
Parameter name: src

Restclient works properly if used with Visual studio community edition and also works fine for Previous version of Profession edition . But it fails with Visual studio Professional edition latest version version 7.6.9 (Xamarin.iOS 12.1.0.15)
Other apis which do not need authentication work fine.

I tried latest RestSharp library version 106.5.4 but it is causing same issue.


One more observation : We have web services running on UAT server as well as Live server. But on UAT our code works just fine.
There is Difference in response headers of  UAT and LIVE.
UAT response headers contain 2 additional headers 
1. connection →keep-alive
2.transfer-encoding →chunked

I have yet to explore the relation of these headers with the issue we are facing.

Please suggest me the best approach to resolve this error.

**Comment by steffenh13** [comment]
You have to manually downgrade Xamarin.iOS and Xamarin.Android versions for now, as I wrote above: https://github.com/mono/mono/issues/9511#issuecomment-436584268

**Comment by amolsarmalkar** [comment]
I want to know Visual studio for mac version corresponding to mono 5.10 . Please share documentation page which has details of visual studio version and its corresponding mono version.

**Comment by steffenh13** [comment]
@amolsarmalkar
You don't need to change the Visual Studio version. Uninstall/delete the currently installed Mono runtime, then install the mentioned Xamarin.Android and Xamarin.iOS versions and do not install any updates for them if Visual Studio prompts you to.

**Comment by amolsarmalkar** [comment]
> @amolsarmalkar
> You don't need to change the Visual Studio version. Uninstall/delete the currently installed Mono runtime, then install the mentioned Xamarin.Android and Xamarin.iOS versions and do not install any updates for them if Visual Studio prompts you to.

The link specified by you for Xamarin.iOS (https://jenkins.xamarin.com/view/Xamarin.MaciOS/job/macios-mac-d15-7/ ) refers to 11.10.1.178 version. Was it a stable version ?

**Comment by flensrocker** [comment]
We have this problem with `System.Net.HttpWebRequest`.

**Comment by beeradmoore** [comment]
For me it appears that it works fine for 4XX requests, its that if the content length header is not set (using transfer-encoding: chunked), that it failed to do anything useful. 

Changing our ASP.NET service to forcefully add content-length fixed any issues we had with any other status code when I woke up this morning to a world of joy.

**Comment by flensrocker** [comment]
We switched to `System.Net.Http.HttpClient`.

**Comment by amolsarmalkar** [comment]
The good news from Restsharp is that they have fixed issue (Please refer the communication at [https://github.com/restsharp/RestSharp/issues/789#issuecomment-456302724] ) and it is about to come in their next release of nuget package 106.7.

**Comment by carvalho-oak** [comment]
> > For the guys using Xamarin encountering this problem:
> > The last working Xamarin.iOS version I could find is 11.10 ([download from Xamarin Jenkins](https://jenkins.xamarin.com/view/Xamarin.MaciOS/job/macios-mac-d15-7/)) and for Xamarin.Android the version 8.3 (using Mono 5.10) seems to be working ([download from Xamarin Jenkins](https://jenkins.xamarin.com/view/Xamarin.Android/job/xamarin-android-builds-d15-7/)).
> > We have to wait on Xamarin to get current versions including the fixed Mono version, the current Xamarin previews don't have the fix yet.
> 
> Starting march 2019, Apple will force using SDK 12 version. We won't be able to upload builds using old sdks.

Please! Release 106.7!

**Comment by carvalho-oak** [comment]
> The good news from Restsharp is that they have fixed issue (Please refer the communication at [https://github.com/[restsharp/RestSharp/issues/789](https://github.com/restsharp/RestSharp/issues/789)#issuecomment-456302724] ) and it is about to come in their next release of nuget package 106.7.

106.8.9 has been released and the issue is not fixed. @amolsarmalkar, could you please confirm if it is working for you?

**Comment by marek-safar** [comment]
@carvalho-oak are you experiencing the exact same issue with the latest restsharp and the steps provided in the description?

/cc @baulig

**Comment by carvalho-oak** [comment]
@marek-safar yes exactly the same as reported by @axa88 at https://github.com/restsharp/RestSharp/issues/1280

**Comment by amolsarmalkar** [comment]
> > The good news from Restsharp is that they have fixed issue (Please refer the communication at [https://github.com/[restsharp/RestSharp/issues/789](https://github.com/restsharp/RestSharp/issues/789)#issuecomment-456302724] ) and it is about to come in their next release of nuget package 106.7.
> 
> 106.8.9 has been released and the issue is not fixed. @amolsarmalkar, could you please confirm if it is working for you?

No latest version 106.8.9 is not working for me. 
We have used OAuth2 and we pass Access token in GET request. As long as the access token is alive, we get proper response. Once the access token expires, the response is received with blank content type , status code 0, content length 0 .Why this scenario fails?
![screen shot 2019-03-05 at 1 02 12 pm](https://user-images.githubusercontent.com/14293740/53788193-15a6ed80-3f47-11e9-9664-0fa4228c1753.png)

**Comment by marek-safar** [comment]
@baulig could you please check you can also reproduce @amolsarmalkar issue

**Comment by greatvova** [comment]
Have same issue when connect to .Net Core written backend. Can't wait to update to 106.7 version.

**Comment by taterjuice** [comment]
I resolved this issue by disabling chunking in my net core api.
I know we don't all have control over the api's we query, but the issue appears to be that the content-type is getting lost after the first chunk. This middle solution solution resolved the issue: https://stackoverflow.com/questions/37966039/disable-chunking-in-asp-net-core/54355016#54355016

**Comment by HonorFace-Shin** [comment]
@baulig , @marek-safar . Any update for @amolsarmalkar issue?
I have same error and all lastest version for visual studio update is not working for me.

**Comment by amitlodha** [comment]
This issue was solved with visual studio 2019

**Comment by HonorFace-Shin** [comment]
@amitlodha Thank you for reply.
I tried newest visual studio 2019, iOS is good works but Andoird is not.
Could you tell me any advice?

**Comment by amitlodha** [comment]
For android you need to update all the library targeting to android 9 and then create a release apk which work fine
