### ISSUE TITLE
DateTime.Now or Timezone information do not transition out of DST for all time zones

### ISSUE THREAD

**Issue by jbatt33** [mono/mono#9664]
### Note
Using Vatican time zone as an example. 

## Steps to Reproduce

1. Turn off NTP time synchronization for linux
> sudo timedatectl set-ntp off
2. Turn off any other network time synchronization services that may be active
3. Set the time zone on the server to the Vatican time zone
> sudo timedatectl set-timezone Europe/Vatican
4. Set the time of the OS to 1 hour and 1 minute before the reported DST Exit datetime of 10/28/2018 3:00:00 AM 
> sudo date 102801592018.00 
5. Run a mono application that prints the time.
6. Wait for an 1 hour and compare the application's time to the OS's time

### Current Behavior

The mono application will not transition out of DST for two hours past DST exit. 

#### OS Linux Run Output
```
$ date
Sun Oct 28 02:59:55 CEST 2018

$ date
Sun Oct 28 02:59:57 CEST 2018

$ date
Sun Oct 28 02:00:00 CET 2018 << System Time correctly drops out of DST

$ date
Sun Oct 28 02:00:02 CET 2018 
```
#### Before transition
```
-----------------------------------------------
DateTime.Now: 10/28/2018 2:59:58 AM
Cleared: DateTime.Now: 10/28/2018 2:59:58 AM
UTC+Offset: 10/28/2018 2:59:58 AM
636762923986794550 - Start: 3/25/2018 2:00:00 AM:636575400000000000 - End: 10/28/2018 3:00:00 AM:636762924000000000 - True
In DST
UTC: 10/28/2018 00:59:58 - Offset: 02:00:00
-----------------------------------------------
```

#### After transition
```
-----------------------------------------------
DateTime.Now: 10/28/2018 3:00:03 AM
Cleared: DateTime.Now: 10/28/2018 3:00:03 AM
UTC+Offset: 10/28/2018 3:00:03 AM
636762924036831780 - Start: 3/25/2018 2:00:00 AM:636575400000000000 - End: 10/28/2018 3:00:00 AM:636762924000000000 - True
Not in DST
UTC: 10/28/2018 01:00:03 - Offset: 02:00:00
-----------------------------------------------
```

#### The UTC+Offset calculation will be correct, but the DateTime.Now will still return the incorrect information. 
```
-----------------------------------------------
DateTime.Now: 10/28/2018 4:14:01 AM
Cleared: DateTime.Now: 10/28/2018 4:14:01 AM
UTC+Offset: 10/28/2018 3:14:01 AM
636762968419149760 - Start: 3/25/2018 2:00:00 AM:636575400000000000 - End: 10/28/2018 3:00:00 AM:636762924000000000 - False
Not in DST
UTC: 10/28/2018 02:14:01 - Offset: 01:00:00
-----------------------------------------------
```

#### Waiting one more hour, the mono application's DateTime.Now will be in sync with the system time
```
-----------------------------------------------
DateTime.Now: 10/28/2018 4:18:39 AM 
Cleared: DateTime.Now: 10/28/2018 4:18:39 AM
UTC+Offset: 10/28/2018 4:18:39 AM
636762971197489090 - Start: 3/25/2018 2:00:00 AM:636575400000000000 - End: 10/28/2018 3:00:00 AM:636762924000000000 - False
Not in DST
UTC: 10/28/2018 03:18:39 - Offset: 01:00:00
-----------------------------------------------
```

### Platforms

Ubuntu 16.04.4 LTS 

```
Mono JIT compiler version 5.4.0.201 (tarball Tue Mar 13 14:55:42 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  x86
        Disabled:      profiler
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

### Mono application's code 

```csharp
using System;
using System.Globalization;
using System.Threading;

namespace NowTest
{
    class Program
    {
        static void Main(string[] args)
        {
            //run forever
            while (true)
            {
                Console.WriteLine("-----------------------------------------------");
                //Print some DateTime.Net information
                Console.WriteLine("DateTime.Now: {0}", DateTime.Now);
                CultureInfo.CurrentCulture.ClearCachedData();
                Console.WriteLine("Cleared: DateTime.Now: {0}", DateTime.Now);
                Console.WriteLine("UTC+Offset: {0}", GetLocalTime());
                
                var currTimeZone = TimeZone.CurrentTimeZone;
                var now = DateTime.Now;
                var dstInfo = currTimeZone.GetDaylightChanges(now.Year);
                var inDST = currTimeZone.IsDaylightSavingTime(now);
                var offset = currTimeZone.GetUtcOffset(now);
                var utcDateTime = DateTime.UtcNow;

                //Print some more information for fun
                Console.WriteLine("{0} - Start: {1}:{2} - End: {3}:{4} - {5}", now.Ticks, dstInfo.Start, dstInfo.Start.Ticks, dstInfo.End, dstInfo.End.Ticks, inDST);
                
                //If I do the match for the ticks, let's see if we are following everything correctly
                if (now.Ticks > dstInfo.Start.Ticks)
                {
                    Console.WriteLine(now.Ticks > dstInfo.End.Ticks ? "Not in DST" : "In DST");
                }

                Console.WriteLine("UTC: {0} - Offset: {1}", utcDateTime.ToString(CultureInfo.InvariantCulture), offset.ToString());
                Console.WriteLine("-----------------------------------------------{0}", Environment.NewLine);
                //Print every 5 seconds for kicks
                Thread.Sleep(5000);
            }
            
        }

        //return the local time using UTC offset and UTC Now
        static DateTime GetLocalTime()
        {
            //Try to clear the cache and see if that helps...
            System.Globalization.CultureInfo.CurrentCulture.ClearCachedData();
            return (DateTime.UtcNow + TimeZone.CurrentTimeZone.GetUtcOffset(DateTime.Now));
        }
    }
}

```

**Comment by jgold6** [comment]
I have another report of this issue. IN this case it caused a serious problem with an app. This past March 9, in CST, the customer's app, which is using DateTime.Now for times, jumped from 7:59 PM to 9:00 PK, seemingly going to CDT (Central Daylight Time) 6 hours early. Doing some more testing I found the following (did not test all time zones):

**In Central ST, time jumped from 3/9 7:59 PM to 9:00 PM.
So between 3/9 8:00 PM CST and 3/10 2:00 AM CST, DateTime.Now shows 1 hour ahead of actual.** 

In Eastern ST, as expected.

In Mountain ST, as expected

In Pacific ST, as expected

**in Alaska ST, time jumped from 3/9 4:59 PM to 6:00 PM
So between 3/9 5:00 PM AST and 3/10 2:00 AM AST, DateTime.Now shows 1 hour ahead of actual.** 

Atlantic ST as expected

**Azores ST (Portugal), time jumps from 3/30 10:59 PM to 3/31 12:00 AM.
So between 3/30 11:00 PM Azores ST and 3/31 12:00 AM Azores ST, DateTime.Now shows 1 hour ahead of actual.** 

Those are all I tested so far

## To reproduce:

1. Create a Mono Console app and write DateTime.Now to the console
2. Set your system time to Central Standard time March 9 at 9 PM.
3. Run the console app

Expected result: Time printed to console should match the system time in the Mac menu bar (or system time of the linux computer)

Actual result: Time printed to console is 1 hour ahead of the system time

## Mono version:
Mono 5.16.0.238 (2018-06/99d74f7f6ee) (64-bit)
Package version: 516000238

**Comment by EgorBo** [comment]
@jbatt33 I can reproduce it on 5.4.0.201 but can't do it on 6.1.x (master) I guess it was fixed by https://github.com/mono/mono/pull/11500 or https://github.com/mono/mono/pull/11232

**Comment by jgold6** [comment]
After going through the list of countries in [this wikipedia page on DST,](https://en.wikipedia.org/wiki/Daylight_saving_time_by_country), these are the areas I found that showed the issue:

Central ST US (Central time Canada seems to be OK)
Alaska ST
Portugal (Azores ST)
Cuba (Cuba ST) 
Turks and Caicos (Eastern ST)

<summary>List of all locales I tested</summary>
<details>

**In Central ST, time jumped from 3/9 7:59 PM to 9:00 PM.
So between 3/9 8:00 PM CST and 3/10 2:00 AM CST, DateTime.Now shows 1 hour ahead of actual.**

In Eastern ST, as expected.

In Mountain ST, as expected, even Arizona that does not observe DST is correct. 

In Pacific ST, as expected

**In Alaska ST, time jumped from 3/9 4:59 PM to 6:00 PM
So between 3/9 5:00 PM AST and 3/10 2:00 AM AST, DateTime.Now shows 1 hour ahead of actual.**

Atlantic ST as expected

**Azores ST (Portugal), time jumps from 3/30 10:59 PM to 3/31 12:00 AM.
So between 3/30 11:00 PM Azores ST and 3/31 12:00 AM Azores ST, DateTime.Now shows 1 hour ahead of actual.**

Now testing by locations in the Wikipedia DST list:

Bahamas (Eastern): as expected

Bermuda (Atlantic): as expected

Canada, Vancouver (Pacific): as expected

Canada, Calgary (mountain): as expected

Canada, Saskatoon Saskatchewan (Central): as expected (Saskatchewan does not observe DST)

Canada, Winnipeg Manitoba (Central): as expected. (note that US Central has the error.) 

Canada, Toronto (Eastern): as expected

Canada, Halifax (Atlantic): as expected

**Cuba, Havana (Cuba Standard Time): time jumps from 3/9 6:59 PM to 8:00 PM. So between 3/9 7:00 PM and 3/10 12:00 AM, DateTime.Now shows 1 hour ahead of actual. (Cuba switches at midnight on second Sunday in March)**

Haiti, Port-au-Prince (Eastern): as expected

Saint Pierre and Miquelon: cannot find in macOS time zone settings

**Turks and Caicos (Eastern): time jumps from 3/9 8:59 PM to 10:00 PM. So between 3/9 9:00 PM and 3/10 2:00 AM, DateTime.Now shows 1 hour ahead of actual. **

United States: see above for Eastern, Central, Mountain, Pacific, and Alaska.

Iran, Tehran (Iran ST): as expected (change on March 22 at 12:00 AM)  

Israel, Jerusalem (Israel ST): as expected

Jordan, Amman (Eastern European ST): as expected (change on 3/29 at 12:00 AM)

Syria, Damascus (Eastern European ST): as expected (change on 3/29 at 12:00 AM)

Greenland, Nuuk (West Greenland ST): as expected (change on 3/30 at 10:00 PM)

Albania, Tirana (Central European ST): as expected (change on 3/31 at 2:00 AM)

Andorra, Andorra la Vella (Central European ST): as expected (change on 3/31 at 2:00 AM)

Austria, Vienna (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Belgium, Brussels (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Bosnia & Herzegovina, Sarajevo (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Bulgaria, Sofia (Eastern European ST): as expected (change on 3/31 at 1:00 AM UTC (3:00 AM local))

Croatia, Zagreb (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Cyprus, Nicosia (Eastern European ST): as expected (change on 3/31 at 1:00 AM UTC (3:00 AM local))

Czechia, Prague (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Denmark, Copenhagen (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Estonia, Tallinn (Eastern European ST): as expected (change on 3/31 at 1:00 AM UTC (3:00 AM local))

Faroe Islands, Thorshavn (Western European ST): as expected (change on 3/31 at 1:00 AM UTC (1:00 AM local))

Finland, Helsinki (Eastern European ST): as expected (change on 3/31 at 1:00 AM UTC (3:00 AM local))

France, Paris (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Germany, Berlin (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Greece, Athens (Eastern European ST): as expected (change on 3/31 at 1:00 AM UTC (3:00 AM local))

Guernsey (UK): cannot find in macOS time zone settings

testing all areas noted in Wikipedia DST article (https://en.wikipedia.org/wiki/Daylight_saving_time_by_country) continued...

Holy See, Vatican City (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Hungary, Budapest (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

UK, Douglas, Isle of Man (GMT+1:00): as expected (change on 3/31 at 1:00 AM UTC (1:00 AM local))

Italy, Rome (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Jersey (UK): cannot find in macOS time zone settings

Kosovo, Pristina (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Latvia, Riga (Eastern European ST): as expected (change on 3/31 at 1:00 AM UTC (3:00 AM local))

Lebanon, Beirut (Eastern European ST): as expected (change on 3/31 at 12:00 AM local)

Liechtenstein, Vaduz (Central European ST): as expected (change on 3/31 at 2:00 AM local)

Lithuania, Vilnius (Eastern European ST): as expected (change on 3/31 at 1:00 AM UTC (3:00 AM local))

Luxembourg, Luxembourg (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Malta, Valletta (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Moldova, Chişinău (Eastern European ST): as expected (change on 3/31 at 2:00 AM local)

Monaco, Monaco (Eastern European ST): as expected (change on 3/31 at 2:00 AM local)

Montenegro, Podgorica (Central European ST): as expected (change on 3/31 at 2:00 AM local)

Netherlands, Amsterdam (Central European ST): as expected (change on 3/31 at 2:00 AM local)

Macedonia, Skopje (Central European ST): as expected (change on 3/31 at 2:00 AM local)

Norway, Oslo (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Poland, Warsaw (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Portugal, Lisbon (Western European ST): as expected (change on 3/31 at 1:00 AM UTC (1:00 AM local))

**Portugal, Ponta Delgada (Azores ST) time jumps from 3/30 10:59 PM to 3/31 12:00 AM. So between 3/30 11:00 PM Azores ST and 3/31 12:00 AM Azores ST, DateTime.Now shows 1 hour ahead of actual.**

Romania, Bucharest (Eastern European ST): as expected (change on 3/31 at 1:00 AM UTC (3:00 AM local))

San Marino, San Marino (Central European ST): as expected (change on 3/31 at 2:00 AM local)

Serbia, Belgrade (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Slovakia, Bratislava (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Slovenia, Ljubljana (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Spain, Madrid (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local))

Sweden, Stockholm (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local)) 

Switzerland, Berne (Central European ST): as expected (change on 3/31 at 1:00 AM UTC (2:00 AM local)) 

Ukraine, Kiev (Eastern European ST): as expected (change on 3/31 at 1:00 AM UTC (3:00 AM local))

United Kingdom, London (British ST): as expected (change on 3/31 at 1:00 AM local)

Mexico, Mexico City (Central ST): as expected (change on 4/7 at 2:00 AM local)
-------------------------------------------------------------
SOUTHERN HEMISPHERE - SPRING BACK:
--------------------------------------------------------------
Chile, Santiago (Chile ST): as expected (change on 4/7 at 12:00 AM (goes back one hour to 11:00 PM 4/6)

New Zealand, Wellington (New Zealand ST): as expected (change on 4/7 at 3:00 AM (goes back one hour to 2:00 AM)

Samoa, Apia (Apia ST): as expected (change on 4/7 at 4:00 AM (goes back one hour to 3:00 AM)

Australia - DST used only in  Australian Capital Territory,  Jervis Bay Territory,  New South Wales, Victoria,  Tasmania,  South Australia

Australian Capital Territory, Canberra (Australian Eastern ST): as expected (change on 4/7 at 3:00 AM (goes back one hour to 2:00 AM) 

New South Wales, Sydney (Australian Eastern ST): as expected (change on 4/7 at 3:00 AM (goes back one hour to 2:00 AM) 

Victoria, Melbourne (Australian Eastern ST): as expected (change on 4/7 at 3:00 AM (goes back one hour to 2:00 AM) 

Tasmania, Hobart (Australian Eastern ST): as expected (change on 4/7 at 3:00 AM (goes back one hour to 2:00 AM) 

South Australia, Adelaide (Australian Central ST): as expected (change on 4/7 at 3:00 AM (goes back one hour to 2:00 AM) 

Paraguay, Asunción (Paraguay ST): as expected (change on 3/24 at 12:00 AM (goes back one hour to 3/23 11:00 PM) 

Brazil - https://en.wikipedia.org/wiki/Daylight_saving_time_in_Brazil - DST end delays one week during Carnival week. Only these south and central states use DST: São Paulo, Rio de Janeiro, Federal District Brasilia, Santa Catarina, Paraná,  Goiás,  Rio Grande do Sul,  Mato Grosso do Sul,  Espírito Santo,  Minas Gerais and  Mato Grosso (some exceptions).

São Paulo, São Paulo (Brasilia ST): as expected (change on 2/17 at 12:00 AM (goes back one hour to 2/16 11:00 PM)

Rio de Janeiro, Rio de Janeiro (Brasilia ST): as expected (change on 2/17 at 12:00 AM (goes back one hour to 2/16 11:00 PM)

Federal District Brasilia, Brasilia (Brasilia ST): as expected (change on 2/17 at 12:00 AM (goes back one hour to 2/16 11:00 PM)

Santa Catarina, Florianopolis (Brasilia ST): as expected (change on 2/17 at 12:00 AM (goes back one hour to 2/16 11:00 PM)

Paraná: Not tested yet

Goiás: Not tested yet

Rio Grande do Sul: Not tested yet

Mato Grosso do Sul: Not tested yet

Espírito Santo: Not tested yet

Minas Gerais: Not tested yet

Mato Grosso (some exceptions): Not tested yet


Fiji: Not tested yet
</details>

**Comment by marek-safar** [comment]
Closing, please reopen if you can still reproduce the issue in dev16.1 release

**Comment by jgold6** [comment]
For the 5 affected time zones noted in my comments above, in Mono 5.18.1.18, DST for those 5 areas are no longer starting DST early. But now they are all starting DST 1 hour late. I.e if the time is supposed to jump from 2:00 AM to 3:00 AM, instead it is jumping from 3:00 AM to 4:00 AM. 

breakdown:

Central Standard time (US), Eastern ST (Turks and Caicos), and Alaska Standard Time:
Should jump from 2:00 AM to 3:00 AM but DateTime.Now jumps from 3:00 AM to 4:00 AM

Cuba Standard Time and  Azores Standard Time:
Should jump from 12:00 AM to 1:00 AM but DateTime.Now jumps from 1:00 AM to 2:00 AM

**Comment by jbatt33** [comment]
Thanks. 

> @jbatt33 I can reproduce it on 5.4.0.201 but can't do it on 6.1.x (master) I guess it was fixed by #11500 or #11232

Thanks for the information. Will pick up either by merging this fix into a 5.x release or wait for 6.0 official release

**Comment by jgold6** [comment]
Checked on mono master. behavior is correct on mono master.

It would be great if we can get the full fix backported to  the current VC for Mac Preview channel (currently has Mono 5.18.1.3, which has original issue I described), and also the internal preview channel (has Mono 5.18.1.18 currently which only changes when the error occurs... I assume this will become the next public preview channel)

**Comment by jgold6** [comment]
@marek-safar 

Testing Xam.Android and Xam.iOS in current public and internal VS for Mac Preview channels, behavior is the same as in mono 5.18.1.18, i.e. in the 5 affected areas, change to DST is one hour late.

breakdown:

Central Standard time (US), Eastern ST (Turks and Caicos), and Alaska Standard Time:
Should jump from 2:00 AM to 3:00 AM but DateTime.Now jumps from 3:00 AM to 4:00 AM

Cuba Standard Time and Azores Standard Time:
Should jump from 12:00 AM to 1:00 AM but DateTime.Now jumps from 1:00 AM to 2:00 AM

Versions:
public Preview:
- XA: 9.3.0.14
- XI: 12.10.0.147
- Mono: 5.18.1.3

internal Preview:
- XA: 9.3.0
- XI: 12.10.0.148
- Mono: 5.18.1.18

**Comment by MaximLipnin** [comment]
According to the latest details the issue wasn't fully resolved. So I'm re-opening it.

**Comment by jgold6** [comment]
Just tested the initially reported issue on the current Xamarin.Android (9.2.3.0) and Mono (5.18.1.3). European/Vatican time is still leaving European Summertime 2 hours later than expected. 

The 5 affected areas that were starting DST late, i.e. Central Standard time (US), Eastern ST (Turks and Caicos), Alaska Standard Time, Cuba Standard Time, and Azores Standard Time, are leaving DST at the correct time.

**Comment by jgold6** [comment]
Other areas tested for leaving DST:

Greenwich Mean Time (Guernsey): Leaves DST one hour later than expected, i.e. at 3:00 am rather than at 2:00 AM on 10/27

Tehran, Iran: Leaves DST 5 hours later than expected, i.e. at 4:00 am on 9/22 rather than at 11:00 PM on 9/21

I am sure there are more, but don't have time for full test right now. 

However the above time zones all work as expected in Mono Master.

**Comment by marek-safar** [comment]
@jgold6 this didn't make it on time for 2018-02 insertion to Xamarin.Android. We have the fix available in dev16.2 P2 version which should be available publicly soon.

**Comment by jgold6** [comment]
@marek-safar Can I assume that the same is true for insertion into Xam.iOS?

**Comment by marek-safar** [comment]
@jgold6 yes

**Comment by jgold6** [comment]
testing 16.2 P2 on Android:

Iran is leaving DST 1 hours late as compared to Android system time. This is improved over the 4 hours late previously tested above, but still not correct. 

European/Vatican time is now leaving DST one hour late as opposed to 2 hours late, so again not fully fixed.

Greenwich Mean Time (Guernsey) is also now leaving DST 1 hour later than expected as compared to Android system time.

**Comment by steveisok** [comment]
@MaximLipnin Please have a look and see if you can determine why we're off.

**Comment by MaximLipnin** [comment]
@steveisok There was another attempt to fix this issue https://github.com/mono/mono/pull/14335 but it was not considered. I'll take a look.

**Comment by jgold6** [comment]
Tested DateTime.Now issue in VS 2019 16.2 P4 ...

Issue still seems to be present in Xam.Android (9.4.0.50):
I tested these locales:
Tehran (Iran Time) leaves DST one hour late
Vatican (Central European Time) leaves DST one hour late
London/Guernsey (GMT) leaves DST one hour late
Kiev (Eastern Europe Time) leaves DST one hour late

Issue seems to be resolved on iOS (12.14.0.110)
I tested these locales:
Tehran (Iran Time)
Vatican (Central Europe Time)
London UK (Greenwich Mean Time)
Kiev, Ukraine (Eastern Europe Time)
And all left DST as expected. Tested on both simulator and device.

**Comment by jgold6** [comment]
I just tested this again on Android and the behavior is correct for those 4 locales when leaving DST. Apparently my Shared mono runtime was not getting updated. Once I removed the shared mono runtime to force an update, DateTime.Now was returning the correct time on the above noted locales after leaving DST.
